export const achievementsAndReportsText = {
  name: 'Achievements and reports',
  capabilities: {
    'achievements-and-reports.achievements.read': 'Read achievements',
    'achievements-and-reports.achievements.record': 'Record achievements',
    'achievements-and-reports.annual-report.manage': 'Manage the annual report',
  },
  settings: {
    'achievements-and-reports.report_year_start': 'Annual report year start',
  },
  tabs: { timeline: 'Timeline', contributions: 'Contributions', reports: 'Annual reports' },
  timeline: {
    scopes: { unit: 'This unit', national: 'General Council', all: 'All branches' },
    none: 'No achievements have been recorded yet.',
    record: 'Record an achievement',
    officers: 'Officers involved: {names}',
    withdrawn: 'Withdrawn',
    locked: 'Locked: its year’s annual report is finalised.',
    change: 'Change',
    withdraw: 'Withdraw',
    restore: 'Bring back',
    photos: 'Photos',
    viewPhoto: 'View {name}',
    removePhoto: 'Take off {name}',
    addPhoto: 'Add a photo',
    adding: 'Adding…',
  },
  form: {
    heading: 'Record an achievement',
    changeHeading: 'Change the achievement',
    title: 'Title',
    date: 'Date',
    category: 'Category',
    description: 'Description',
    officers: 'Officers involved',
    officersHint: 'Anyone who has served in this unit, past officers included.',
    save: 'Save',
    cancel: 'Cancel',
    choose: 'Choose…',
  },
  contributions: {
    heading: 'Officers’ contributions',
    none: 'Nobody has served here yet.',
    roles: 'Roles held',
    term: '{role}, {unit}: {start} to {end}',
    toDate: 'now',
    achievements: 'Achievements',
    noAchievements: 'No achievements credited yet.',
    achievement: '{date}: {title} ({category})',
  },
  reports: {
    heading: 'Annual reports',
    none: 'No annual reports yet.',
    year: 'Year',
    start: 'Start the {year} report',
    statuses: { Draft: 'Draft', Finalised: 'Finalised' },
    report: 'The {year} report',
    draftNote:
      'A draft shows the latest figures from the records. Only the summary is written here.',
    summaryLabel: 'The branch’s summary (optional)',
    saveSummary: 'Save the summary',
    saved: 'Saved',
    finalise: 'Finalise and lock',
    finaliseConfirm:
      'Finalise the {year} report? Its content is frozen, its PDF filed in the archive, and it can never be changed.',
    provisionalWarning:
      'The financial year is not closed yet, so the Treasury figures will be marked provisional.',
    confirm: 'Yes, finalise it',
    cancel: 'Cancel',
    finalising: 'Finalising…',
    finalisedOn: 'Finalised on {date} by {name}',
    download: 'Download the PDF',
  },
  reportPdf: {
    title: 'Annual report {year}: {unit}',
    period: 'From {start} to {end}',
    summary: 'Summary',
    achievements: 'Achievements',
    events: 'Events completed',
    meetings: 'Meetings held',
    treasury: 'Treasury',
    officers: 'Current officers',
    none: 'None.',
    notInUse: '{service} is not in use in this unit.',
    achievementLine: '{date}: {title} ({category}). {officers}',
    listSeparator: ', ',
    eventLine: '{date}: {name}',
    meetingLine: '{date}: {type}',
    officerLine: '{name}, {role}',
    provisional: 'Provisional: the financial year is not yet closed.',
    treasuryYear: 'Financial year {start} to {end}',
    startBalance: 'Balance at the start: {amount}',
    openingBalances: 'Opening balances entered: {amount}',
    credits: 'Money in: {amount}',
    debits: 'Money out: {amount}',
    endBalance: 'Balance at the end: {amount}',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its achievements are read-only.',
    'branches.not-found': 'This unit does not exist.',
    'service.switched-off': 'Achievements and reports is switched off for this unit.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
    'request.invalid': 'Check the details and try again.',
    'pdf.not-available': 'PDFs are not available here. They work on the preview site.',
    'files.type-not-allowed': 'This file type is not allowed here.',
    'files.too-large': 'This file is larger than the limit.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'achievements-and-reports.stale':
      'Someone else changed this. Reload the page to see their change.',
    'achievements-and-reports.locked': 'This is locked: its year’s annual report is finalised.',
    'achievements-and-reports.future-date': 'The date cannot be in the future.',
    'achievements-and-reports.category-not-in-list': 'Choose a category from the list.',
    'achievements-and-reports.not-an-officer': 'Choose people who have served in this unit.',
    'achievements-and-reports.achievement-not-found': 'This achievement does not exist.',
    'achievements-and-reports.already-withdrawn': 'This achievement is already withdrawn.',
    'achievements-and-reports.not-withdrawn': 'This achievement is not withdrawn.',
    'achievements-and-reports.photo-not-found': 'This photo does not exist.',
    'achievements-and-reports.person-not-found': 'This person has not served here.',
    'achievements-and-reports.year-not-ended':
      'This year has not ended yet, so its report cannot be started.',
    'achievements-and-reports.already-started': 'This year’s report has already been started.',
    'achievements-and-reports.report-not-found': 'This report does not exist.',
    'achievements-and-reports.report-not-finalised': 'This report is not finalised yet.',
  },
};
