/** Brief 25 C3: the branding and letterhead screen. */
export const brandingText = {
  intro:
    'The organisation name, and the main and accent colours used for headings, rules and accents on the portal and in its documents. Text stays black on white.',
  nameEn: 'Organisation name in English',
  nameAr: 'Organisation name in Arabic',
  mainColour: 'Main colour',
  accentColour: 'Accent colour',
  sampleHeading: 'Heading',
  contrastOk: '{ratio}:1 against white: reads well',
  contrastTooLow: '{ratio}:1 against white: too pale to read (needs 4.5:1)',
  save: 'Save',
  files: 'Files',
  uploaded: 'uploaded',
  notUploaded: 'not uploaded yet',
  logo: 'Logo',
  logoHint: 'A PNG, as it should appear on the letterhead.',
  icon: 'Square icon',
  iconHint: 'A square PNG, at least 512 pixels. It becomes the icon on phones’ home screens.',
  latinFont: 'Latin font',
  arabicFont: 'Arabic font',
  fontHint: 'A font file (.woff2, .ttf or .otf), used on the screens and in the documents.',
  logoPosition: 'Logo position on the letterhead',
  logoPositionHint: 'In Arabic letters it is mirrored: left becomes the start of the line.',
  positions: { left: 'Left', centre: 'Centre', right: 'Right' },
  letterhead: 'Letterhead',
  previewIn: { en: 'In English', ar: 'In Arabic' },
  previewPdf: 'Preview PDF',
  sample: {
    logo: 'Logo',
    paragraphs:
      'Dear colleague,\n\nThis is how a letter from the portal looks on the letterhead.\n\nWith best wishes,',
    signer: { name: 'The signing officer', role: 'Their role', unit: 'Their unit' },
  },
  refusals: {
    'pdf.not-available': 'PDF previews are not available here. They work on the preview site.',
    'branding.icon-not-square': 'The icon must be a square image.',
    'files.type-not-allowed': 'This file type is not allowed for it. See the file settings.',
    'files.too-large': 'This file is larger than its limit. See the file settings.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'files.upload-failed': 'The upload did not finish. Try again.',
    'setting.not-configured': 'This waits for its file settings to be set.',
    'branding.no-national-unit': 'The General Council unit does not exist yet.',
    'request.invalid':
      'Check what you entered: the English name is needed, and each colour must read on white.',
  },
};
