export const calendarText = {
  name: 'Calendar',
  capabilities: {
    'calendar.calendar.read': 'Read the calendar',
    'calendar.community-dates.manage': 'Manage community dates',
  },
  settings: {
    'calendar.feed_includes_all_branch_dates': 'Phone feed includes all-branches community dates',
  },
  views: { label: 'View', month: 'Month', week: 'Week', list: 'List' },
  scope: { label: 'Show', branch: 'This branch', all: 'All branches' },
  filters: {
    kinds: 'Show',
    branches: 'Branches',
    meeting: 'Meetings',
    event: 'Events',
    community: 'Community dates',
  },
  previous: 'Earlier',
  weekOf: 'Week beginning {date}',
  close: 'Close',
  next: 'Later',
  none: 'Nothing in this period.',
  kinds: { meeting: 'Meeting', event: 'Event', community: 'Community date' },
  forAllBranches: 'For all branches',
  retired: 'Retired',
  readOnly: 'Changed only in its own service',
  add: 'Add a community date',
  edit: 'Change',
  retire: 'Retire',
  restore: 'Bring back',
  form: {
    title: 'Title',
    startDate: 'Date (first day)',
    endDate: 'Last day (for several days)',
    startTime: 'Time (optional)',
    description: 'Description (optional)',
    forAllBranches: 'For all branches',
    save: 'Save',
    cancel: 'Cancel',
  },
  clash: 'On this day, the unit also has: {items}. You can still save.',
  feed: {
    heading: 'Phone calendar',
    explanation:
      "Subscribe once on your phone, and the portal's dates appear in your phone's calendar and stay up to date.",
    none: 'You have no phone calendar link yet.',
    since: 'Your link was made on {date}.',
    make: 'Make a link',
    remake: 'Make a new link (the old one stops working)',
    shownOnce: 'Your link — copy it now; it is shown only this once:',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its calendar is read-only.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
    'request.invalid': 'Check the details: the last day cannot be before the first.',
    'calendar.all-branches-general-council-only':
      'Only the General Council adds dates for all branches.',
    'calendar.community-date-not-found': 'This date no longer exists.',
    'calendar.stale': 'Someone else changed this date. Reload the page to see their change.',
    'calendar.already-retired': 'This date is already retired.',
    'calendar.not-retired': 'This date is not retired.',
  },
};
