export const communicationHubText = {
  name: 'Communication hub',
  capabilities: {
    'communication-hub.noticeboard.read': 'Read the Noticeboard',
    'communication-hub.noticeboard.manage': 'Manage the Noticeboard',
  },
  settings: {
    'communication-hub.alert_types_for_new_officers': 'Alert types switched on for new officers',
  },
  sections: { label: 'Communication hub sections', noticeboard: 'Noticeboard' },
  noticeboard: {
    heading: 'Noticeboard',
    none: 'No notices yet.',
    post: 'Post a notice',
    postedBy: 'Posted by {name} on {date}',
    automatic: 'Automatic',
    automaticKinds: {
      'event-published': 'Event published: {title}, {date}',
      'meeting-scheduled': 'Meeting scheduled: {title}, {date}',
      'meeting-held': 'Meeting has taken place: {title}, {date}',
    },
    retired: 'Retired',
    edit: 'Change',
    retire: 'Retire',
    restore: 'Bring back',
  },
  noticeForm: {
    title: 'Title',
    body: 'Text',
    withVote: 'Put this notice to a vote',
    question: 'Question',
    option: 'Option {number}',
    addOption: 'Add an option',
    removeOption: 'Remove',
    closesOn: 'Closing date (the vote closes at the end of this day)',
    eligibility: 'Who can vote',
    eligibilities: {
      unit: 'All officers of the unit',
      roles: 'Officers holding chosen roles',
      named: 'Named officers',
    },
    roles: 'Roles',
    officers: 'Officers',
    voteLocked:
      'Someone has already voted, so the vote can no longer be changed. Its closing date can still be moved later, on the notice.',
    save: 'Save',
    cancel: 'Cancel',
  },
  vote: {
    closesOn: 'Voting closes at the end of {date}.',
    closed: 'Voting closed at the end of {date}.',
    cast: 'Vote',
    youVoted: 'You voted: {option}.',
    notEligible: 'You are not one of the voters for this vote.',
    resultsLater: 'Results are shown when voting closes.',
    results: 'Results',
    count: 'Votes: {count}',
    extend: 'Move the closing date later',
    newClosesOn: 'New closing date',
    extendSave: 'Move',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its Noticeboard is read-only.',
    'request.invalid':
      'Check the details: a vote needs a question and at least two different options.',
    'communication-hub.notice-not-found': 'This notice no longer exists.',
    'communication-hub.stale':
      'Someone else changed this notice. Reload the page to see their change.',
    'communication-hub.already-retired': 'This notice is already retired.',
    'communication-hub.not-retired': 'This notice is not retired.',
    'communication-hub.automatic-post-unchanged': 'An automatic post can’t be changed.',
    'communication-hub.vote-locked':
      'Someone has already voted, so the vote can no longer be changed.',
    'communication-hub.closing-date-past': 'The closing date can’t be in the past.',
    'communication-hub.no-eligible-voters': 'Nobody would be able to vote: choose other voters.',
    'communication-hub.role-not-found': 'One of the chosen roles no longer exists.',
    'communication-hub.not-a-current-officer':
      'Only current officers of the unit can be named as voters.',
    'communication-hub.vote-not-found': 'This vote no longer exists.',
    'communication-hub.vote-closed': 'Voting has closed.',
    'communication-hub.not-eligible': 'You are not one of the voters for this vote.',
    'communication-hub.already-voted': 'You have already voted, and a vote can’t be changed.',
    'communication-hub.option-not-found': 'That option is not part of this vote.',
    'communication-hub.closing-date-not-later':
      'The new closing date must be later than the current one.',
  },
  alertTypes: {
    notices: 'New notices',
    votes: 'Votes',
    circulars: 'National circulars',
    replies: 'Replies',
    requests: 'Requests',
  },
};
