export const communicationHubText = {
  name: 'Communication hub',
  capabilities: {
    'communication-hub.noticeboard.read': 'Read the Noticeboard',
    'communication-hub.noticeboard.manage': 'Manage the Noticeboard',
    'communication-hub.circulars.send': 'Send national circulars',
    'communication-hub.discussions.start': 'Start topic discussions',
    'communication-hub.requests.send': 'Send and close requests between branches',
  },
  settings: {
    'communication-hub.alert_types_for_new_officers': 'Alert types switched on for new officers',
    'communication-hub.push_max_attempts': 'Phone alert attempts',
    'communication-hub.undelivered_alert_retention_days': 'Undelivered phone alerts kept (days)',
  },
  sections: {
    label: 'Communication hub sections',
    noticeboard: 'Noticeboard',
    circulars: 'National circulars',
    roleNetworks: 'Role networks',
    discussions: 'Topic discussions',
    requests: 'Requests between branches',
    alertSettings: 'Notification settings',
  },
  noticeboard: {
    heading: 'Noticeboard',
    none: 'No notices yet.',
    post: 'Post a notice',
    postedBy: 'Posted by {name} on {date}',
    automatic: 'Automatic',
    automaticKinds: {
      'event-published': 'Event published: {title}, {date}',
      'meeting-scheduled': 'Meeting scheduled: {title}, {date}',
      'meeting-held': 'Meeting has taken place: {title}, {date}',
    },
    retired: 'Retired',
    edit: 'Change',
    retire: 'Retire',
    restore: 'Bring back',
  },
  noticeForm: {
    title: 'Title',
    body: 'Text',
    withVote: 'Put this notice to a vote',
    question: 'Question',
    option: 'Option {number}',
    addOption: 'Add an option',
    removeOption: 'Remove',
    closesOn: 'Closing date (the vote closes at the end of this day)',
    eligibility: 'Who can vote',
    eligibilities: {
      unit: 'All officers of the unit',
      roles: 'Officers holding chosen roles',
      named: 'Named officers',
    },
    roles: 'Roles',
    officers: 'Officers',
    voteLocked:
      'Someone has already voted, so the vote can no longer be changed. Its closing date can still be moved later, on the notice.',
    save: 'Save',
    cancel: 'Cancel',
  },
  vote: {
    closesOn: 'Voting closes at the end of {date}.',
    closed: 'Voting closed at the end of {date}.',
    cast: 'Vote',
    youVoted: 'You voted: {option}.',
    notEligible: 'You are not one of the voters for this vote.',
    resultsLater: 'Results are shown when voting closes.',
    results: 'Results',
    count: 'Votes: {count}',
    extend: 'Move the closing date later',
    newClosesOn: 'New closing date',
    extendSave: 'Move',
  },
  circulars: {
    heading: 'National circulars',
    none: 'No circulars yet.',
    sentOn: 'Sent on {date}',
    opened: 'Opened by your branch on {date}',
    notOpened: 'Not yet opened by your branch',
    open: 'Read',
    close: 'Close',
    send: 'Send a circular',
    sentBy: 'Sent by {name} on {date}',
    toAll: 'To all branches',
    toChosen: 'To chosen branches',
    openedCount: 'Opened by {opened} of {total} branches',
    branchOpened: 'opened on {date}',
    branchNotOpened: 'not yet opened',
    form: {
      title: 'Title',
      body: 'Text',
      recipients: 'Send to',
      allBranches: 'All branches',
      chosenBranches: 'Chosen branches',
      branches: 'Branches',
      save: 'Send',
      cancel: 'Cancel',
      final: 'A circular can’t be changed once sent.',
    },
  },
  conversation: {
    removed: 'Message removed by its author.',
    remove: 'Remove',
    write: 'Your message',
    send: 'Send',
    none: 'No messages yet.',
    by: '{name} ({units}), {date}',
    byName: '{name}, {date}',
  },
  roleNetworks: {
    heading: 'Role networks',
    none: 'You hold no role with a network where the hub is switched on.',
    explanation:
      'Everyone holding this role now, in any branch or the General Council, shares this conversation.',
  },
  discussions: {
    heading: 'Topic discussions',
    none: 'You have not been invited to any discussions.',
    start: 'Start a discussion',
    startedBy: 'Started by {name} on {date}',
    members: 'In this discussion',
    open: 'Open',
    close: 'Close',
    invite: 'Invite more officers',
    inviteWarning:
      'Anyone you add will see everything already said in this discussion, not just new messages. The people already in it should know this.',
    inviteSave: 'Invite',
    removeMember: 'Remove',
    leave: 'Leave this discussion',
    form: {
      subject: 'Subject',
      body: 'First message',
      invitees: 'Officers to invite',
      save: 'Start',
      cancel: 'Cancel',
    },
  },
  requests: {
    heading: 'Requests between branches',
    none: 'No requests yet.',
    send: 'Send a request',
    sent: 'Sent by your branch',
    received: 'From {branch}',
    askedBy: 'Asked by {name} on {date}',
    toAll: 'To all other units',
    to: 'To: {branches}',
    statuses: { Open: 'Open', Answered: 'Answered', Closed: 'Closed' },
    open: 'Open',
    closeView: 'Close',
    closeRequest: 'Close this request',
    closedNote: 'This request is closed and takes no more replies.',
    form: {
      subject: 'Subject',
      body: 'What you are asking for',
      recipients: 'Send to',
      allBranches: 'All other units (the branches and the General Council)',
      chosenBranches: 'Chosen units',
      branches: 'Units',
      save: 'Send',
      cancel: 'Cancel',
    },
  },
  phoneAlerts: {
    'communication-hub.notice': 'New notice',
    'communication-hub.vote': 'New vote',
    'communication-hub.vote-result': 'Vote result',
    'communication-hub.circular': 'National circular',
    'communication-hub.request': 'New request',
    'communication-hub.reply': 'New reply',
  },
  alertSettings: {
    heading: 'Notification settings',
    intro:
      'Choose which alerts you receive, in the portal and on your phone. National circulars always notify.',
    startingNote: 'You have not chosen yet, so you get the alerts new officers start with.',
    notSet:
      'Your administrator has not set the alerts new officers start with yet. Choose your own below.',
    alwaysOn: 'always on',
    save: 'Save',
    saved: 'Saved.',
    phone: 'Alerts on this device',
    phoneOn: 'This device receives phone alerts.',
    phoneOff: 'This device does not receive phone alerts.',
    turnOn: 'Receive alerts on this device',
    turnOff: 'Stop alerts on this device',
    blocked:
      'This browser blocks notifications for the portal. Allow them in its settings, then try again.',
    unsupported: 'This browser cannot receive phone alerts.',
    iphone: 'On an iPhone',
    notSetUp: 'Phone alerts are not set up yet. Please ask your administrator.',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its Noticeboard is read-only.',
    'request.invalid':
      'Check the details: a vote needs a question and at least two different options.',
    'communication-hub.notice-not-found': 'This notice no longer exists.',
    'communication-hub.stale':
      'Someone else changed this notice. Reload the page to see their change.',
    'communication-hub.already-retired': 'This notice is already retired.',
    'communication-hub.not-retired': 'This notice is not retired.',
    'communication-hub.automatic-post-unchanged': 'An automatic post can’t be changed.',
    'communication-hub.vote-locked':
      'Someone has already voted, so the vote can no longer be changed.',
    'communication-hub.closing-date-past': 'The closing date can’t be in the past.',
    'communication-hub.no-eligible-voters': 'Nobody would be able to vote: choose other voters.',
    'communication-hub.role-not-found': 'One of the chosen roles no longer exists.',
    'communication-hub.not-a-current-officer':
      'Only current officers of the unit can be named as voters.',
    'communication-hub.vote-not-found': 'This vote no longer exists.',
    'communication-hub.vote-closed': 'Voting has closed.',
    'communication-hub.not-eligible': 'You are not one of the voters for this vote.',
    'communication-hub.already-voted': 'You have already voted, and a vote can’t be changed.',
    'communication-hub.option-not-found': 'That option is not part of this vote.',
    'communication-hub.closing-date-not-later':
      'The new closing date must be later than the current one.',
    'communication-hub.general-council-only': 'Only the General Council sends national circulars.',
    'communication-hub.branch-not-found': 'One of the chosen branches no longer exists.',
    'communication-hub.no-branches': 'There are no branches to send to.',
    'communication-hub.circular-not-found': 'This circular was not sent to your branch.',
    'communication-hub.message-not-found': 'This message no longer exists.',
    'communication-hub.author-only': 'Only its author can remove a message.',
    'communication-hub.already-removed': 'This message has already been removed.',
    'communication-hub.discussion-not-found': 'You are not in this discussion.',
    'communication-hub.starter-only':
      'Only the person who started the discussion can invite others.',
    'communication-hub.request-not-found': 'This request does not involve your unit.',
    'communication-hub.request-closed': 'This request is closed and takes no more replies.',
    'communication-hub.not-a-member': 'This officer is not in the discussion.',
    'communication-hub.starter-stays': 'The person who started a discussion stays in it.',
  },
  alertTypes: {
    notices: 'New notices',
    votes: 'Votes',
    circulars: 'National circulars',
    replies: 'Replies',
    requests: 'Requests',
  },
};
