export const correspondenceAndLettersText = {
  name: 'Correspondence and letters',
  capabilities: {
    'correspondence-and-letters.registers.read': 'Read the letter registers',
    'correspondence-and-letters.letters-out.write': 'Write letters',
    'correspondence-and-letters.letters-in.record': 'Record letters in',
  },
  settings: {
    'correspondence-and-letters.reference_format_out': 'Reference number format: letters out',
    'correspondence-and-letters.reference_format_in': 'Reference number format: letters in',
  },
  tabs: { out: 'Letters out', in: 'Letters in' },
  statuses: {
    Received: 'Received',
    'Awaiting reply': 'Awaiting reply',
    Replied: 'Replied',
    'No reply needed': 'No reply needed',
  },
  lettersOut: {
    heading: 'Letters out',
    none: 'No letters have been written yet.',
    write: 'Write a letter',
    reference: 'Reference',
    date: 'Date',
    recipient: 'Recipient',
    subject: 'Subject',
    sentBy: 'Sent by',
  },
  lettersIn: {
    heading: 'Letters in',
    none: 'No letters have been recorded yet.',
    record: 'Record a letter received',
    reference: 'Reference',
    dateReceived: 'Date received',
    sender: 'Sender',
    subject: 'Subject',
    handler: 'Handled by',
    status: 'Status',
  },
  write: {
    heading: 'Write a letter',
    template: 'Template',
    national: '{title} (General Council)',
    recipientName: 'Recipient’s name',
    recipientAddress: 'Recipient’s address (optional)',
    subject: 'Subject, for the register',
    subjectHint: 'Printed on the letter only if its template has a subject line.',
    signAs: 'Sign as',
    replyTo: 'In reply to (optional)',
    notAReply: 'Not a reply',
    answerable: '{reference}: {sender}, {subject}',
    noTemplates: 'There are no letter templates to write from yet.',
    noRoles: 'You hold no role in this unit today, so you cannot sign a letter here.',
    preview: 'Preview',
    previewPdf: 'Preview PDF',
    generate: 'Generate the letter',
    generating: 'Generating…',
    lockedNote: 'Once generated, the letter is numbered, filed and can never be changed.',
    choose: 'Choose…',
  },
  record: {
    heading: 'Record a letter received',
    file: 'Scan or photo of the letter',
    fileHint: 'A letter of several pages is uploaded as one PDF.',
    dateReceived: 'Date received',
    sender: 'Sender',
    subject: 'Subject',
    handler: 'Handled by',
    answers: 'Answers our letter (optional)',
    notAnAnswer: 'Not an answer to one of ours',
    letterOut: '{reference}: {recipient}, {subject}',
    save: 'Record the letter',
    saving: 'Recording…',
    choose: 'Choose…',
  },
  letter: {
    download: 'Download',
    recipientAddress: 'Address',
    signedBy: 'Signed by {name}, {role}',
    handler: 'Handled by',
    changeHandler: 'Change',
    saveLink: 'Save the link',
    moveTo: 'Mark as: {status}',
    writeReply: 'Write a reply',
    exchange: 'The whole exchange',
    exchangeOut: 'Out {reference}, {date}: to {party}, {subject}',
    exchangeIn: 'In {reference}, {date}: from {party}, {subject}',
    thisLetter: '(this letter)',
  },
  letterPdf: {
    reference: 'Our reference: {reference}',
    date: 'Date: {date}',
    referenceToCome: '[given when the letter is generated]',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its letters are read-only.',
    'branches.not-found': 'This unit does not exist.',
    'service.switched-off': 'Correspondence is switched off for this unit.',
    'setting.not-configured':
      'This has not been set up yet: the reference formats, the letterhead or the file rules. Please ask your administrator.',
    'request.invalid': 'Check the details and try again.',
    'pdf.not-available': 'PDFs are not available here. They work on the preview site.',
    'files.type-not-allowed': 'This file type is not allowed here.',
    'files.too-large': 'This file is larger than the limit.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'correspondence-and-letters.template-not-found': 'Choose one of the templates listed.',
    'correspondence-and-letters.field-missing': 'Fill in every field of the letter.',
    'correspondence-and-letters.not-your-role': 'Sign with a role you hold in this unit today.',
    'correspondence-and-letters.not-answerable':
      'That letter cannot be answered: it is marked as needing no reply.',
    'correspondence-and-letters.letter-not-found': 'This letter does not exist.',
    'correspondence-and-letters.future-date': 'The date received cannot be in the future.',
    'correspondence-and-letters.not-an-officer': 'Choose from the unit’s current officers.',
    'correspondence-and-letters.wrong-status': 'The letter cannot move to that status.',
    'correspondence-and-letters.closed':
      'This letter is closed, so who handles it can no longer change.',
    'correspondence-and-letters.stale':
      'Someone else changed this letter. Reload the page to see their change.',
    'correspondence-and-letters.busy':
      'Other letters were being numbered at the same moment. Please try again.',
  },
};
