export const documentsArchiveText = {
  name: 'Documents archive',
  capabilities: {
    'documents-archive.documents.read': 'Read the archive',
    'documents-archive.documents.upload': 'Upload to the archive',
  },
  search: {
    heading: 'Search the archive',
    title: 'Title',
    category: 'Category',
    unit: 'Branch',
    any: 'Any',
    dateField: 'Date',
    documentDate: 'Document date',
    filedDate: 'Filing date',
    from: 'From',
    to: 'To',
    submit: 'Search',
    noResults: 'No documents match.',
  },
  document: {
    back: 'Back to the archive',
    automatic: 'Filed automatically; read-only',
    uploaded: 'Uploaded',
    documentDate: 'Document date: {date}',
    filedOn: 'Filed on {date} by {name}',
    filedOnNoName: 'Filed on {date}',
    versions: 'Versions',
    version: 'Version {version}: {fileName}, dated {documentDate}, added on {date}',
    newVersion: 'Add a new version',
    newVersionExplanation:
      'Earlier versions are kept. The new version has its own date, such as the date an amendment was made.',
    versionDate: "The new version's own date",
    addVersion: 'Add version',
    versionAdded: 'The new version is in the archive.',
    download: 'Download',
  },
  upload: {
    heading: 'Upload a document',
    explanation: "Official documents for your unit's archive, in Governance or General.",
    file: 'File',
    title: 'Title',
    description: 'Description',
    documentDate: "The document's own date",
    category: 'Category',
    submit: 'Upload',
    done: 'The document is in the archive.',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'documents-archive.not-found': 'This document does not exist, or is not yours to see.',
    'branches.inactive': 'This branch is inactive, so its archive is read-only.',
    'files.type-not-allowed': 'This file type is not allowed for documents.',
    'files.too-large': 'This file is larger than the limit for documents.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'files.upload-failed': 'The upload did not finish. Try again.',
    'files.not-uploaded': 'The upload did not finish. Try again.',
    'documents-archive.automatic-filing-locked':
      'This document was filed automatically and is locked, so it has no new versions.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
  },
};
