/** Brief 14 C1: elections in the register. */
export const electionsText = {
  noElections: 'No elections recorded yet.',
  recordHeading: 'Record an election',
  electionDate: 'Election date',
  corrects: 'Correction of',
  notACorrection: 'Not a correction',
  record: 'Record election',
  correction: 'A correction of an earlier confirmed election',
  statuses: { Draft: 'Draft', Confirmed: 'Confirmed' },
  electionOf: 'Election of {date}',
  termsStarted: 'New terms started on {date}',
  locked: 'This election is confirmed and locked. A correction is recorded as a new election.',
  positions: 'Positions',
  noPositions: 'No positions yet.',
  seats: 'Seats',
  seatCount: '{seats} seat(s)',
  addPosition: 'Add position',
  removePosition: 'Remove the {role} position',
  candidate: 'Candidate',
  chooseCandidate: 'Choose a candidate',
  someoneNew: 'Someone new',
  addCandidate: 'Add candidate',
  removeCandidate: 'Remove {name}',
  votes: '{votes} votes',
  votesFor: 'Votes for {name}',
  elected: 'Elected',
  results: 'Results',
  saveResults: 'Save results',
  confirmExplanation:
    'Confirming ends the outgoing terms and starts the elected officers’ terms on the date below. It cannot be undone.',
  confirmChecked: 'I have checked the results.',
  termsStartDate: 'New terms start on',
  confirm: 'Confirm results',
  refusals: {
    'elections.confirmed-is-locked': 'This election is confirmed and locked.',
    'elections.corrects-must-be-confirmed-of-unit':
      'A correction must refer to a confirmed election of this unit.',
    'elections.start-before-election': 'New terms cannot start before the election.',
    'elections.no-positions': 'Add at least one position first.',
    'elections.results-incomplete': 'Record the votes of every candidate first.',
    'elections.seats-not-filled':
      'Each position needs exactly as many elected candidates as it has seats.',
    'elections.already-a-candidate': 'This person is already a candidate for this position.',
    'elections.position-not-found': 'This position no longer exists.',
    'elections.candidate-not-found': 'This candidate no longer exists.',
    'elections.not-found': 'This election no longer exists.',
    'roles.not-found': 'This role cannot be used in this unit.',
    'branches.inactive': 'This branch is inactive, so its register is read-only.',
    'setting.not-configured':
      'This waits for the data administrator: the language new officers start with is not set.',
    'request.invalid': 'Check the fields and try again.',
  },
};
