/** Brief 16 C1, C2 and P20, D-099, D-106, D-108, D-109: equipment and loans. */
export const equipmentText = {
  heading: 'Equipment',
  none: 'No equipment yet.',
  add: 'Add equipment',
  item: 'Item',
  quantity: 'Quantity',
  location: 'Where it is kept',
  condition: 'Condition',
  noConditions: 'The equipment conditions list is empty. Please ask your administrator.',
  summary: '{quantity} · {location} · {condition}',
  outOnLoan: '{count} out on loan',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Change details',
  retire: 'Retire',
  restore: 'Bring back',
  national: 'General Council',
  retired: 'Retired',
  onLoanNow: 'Out on loan now',
  nothingOut: 'Nothing is out on loan.',
  loans: 'Loans',
  lend: 'Lend',
  borrower: 'Borrower',
  borrowedOn: 'Date borrowed',
  dueBack: 'Due back',
  returnedOn: 'Date it came back',
  loanSummary: '{quantity} × {item} to {borrower}, from {borrowed}, due back {due}',
  loanReturned: 'Came back on {date}',
  correct: 'Correct',
  recordReturn: 'Record return',
  history: 'History',
  changes: { lent: 'Lent', corrected: 'Corrected', returned: 'Returned' },
  historyEntry: '{change} by {name} on {date}: {quantity} to {borrower}, {borrowed} to {due}',
  refusals: {
    'permission.denied': 'You may not do this.',
    'resources-library.stale': 'Someone else changed this. Reload the page to see their change.',
    'resources-library.equipment-not-found': 'This item no longer exists.',
    'resources-library.loan-not-found': 'This loan no longer exists.',
    'resources-library.already-retired': 'This item is already retired.',
    'resources-library.not-retired': 'This item is not retired.',
    'resources-library.condition-not-offered': 'Choose a condition from the list.',
    'resources-library.equipment-retired': 'This item is retired, so it cannot be lent.',
    'resources-library.over-lent':
      'Only {left} left to lend: {quantity} owned and {out} already out on loan. You asked for {requested}.',
    'resources-library.below-loans':
      'The quantity cannot be {quantity}: {out} are out on loan now.',
    'resources-library.loan-returned': 'This loan has been returned, so it can no longer change.',
    'resources-library.returned-before-borrowed':
      'It cannot come back before the day it was borrowed.',
    'branches.inactive': 'This branch is inactive, so its library is read-only.',
    'request.invalid': 'Check the details: it is due back on or after the day it was borrowed.',
  },
};
