export const eventOrganiserText = {
  name: 'Event organiser',
  capabilities: {
    'event-organiser.events.read': 'See events',
    'event-organiser.events.create': 'Create events',
    'event-organiser.events.approve': 'Approve events',
    'event-organiser.events.manage': 'Manage events',
    'event-organiser.events.close': 'Close events',
    'event-organiser.templates.manage': 'Manage event templates',
  },
  settings: {
    'event-organiser.status_may_move_backwards': 'Event status may move backwards',
    'event-organiser.cancelled_tasks_count_in_progress': 'Cancelled tasks count in progress',
  },
  sections: { label: 'Event organiser sections', events: 'Events', templates: 'Templates' },
  list: { heading: 'Events', none: 'There are no events yet.', add: 'New event' },
  form: {
    name: 'Name',
    type: 'Type',
    lead: 'Lead officer',
    firstDay: 'Date (first day)',
    startTime: 'Start time (optional)',
    lastDay: 'Last day (optional, for an event over several days)',
    template: 'Start from a template (optional)',
    noTemplate: 'No template',
    save: 'Save',
    cancel: 'Cancel',
  },
  details: { when: 'When', cancelled: 'Cancelled: {reason}', edit: 'Change details' },
  status: {
    heading: 'Status',
    approve: 'Record committee approval',
    moveTo: 'Move to {status}',
    moveBackTo: 'Move back to {status}',
    cancel: 'Cancel the event',
    cancelWarning:
      'A cancel cannot be undone. The event is then closed in the usual way, as cancelled.',
    reason: 'Reason for cancelling',
    confirmCancel: 'Cancel the event',
  },
  publish: {
    heading: 'Publishing',
    targets: { calendar: 'the Calendar', noticeboard: 'the Noticeboard' },
    published: 'Published to {target} on {date}.',
    notYet: 'Not yet published to {target}.',
    switchedOff:
      'Not published to {target}: it is switched off. It can be published once it is back on.',
    publishTo: 'Publish to {target}',
    publishAll: 'Publish to both',
    cancellationPosted: 'The cancellation has been posted on the Noticeboard.',
    cancellationWaiting: 'The cancellation has not been posted on the Noticeboard yet.',
    cancellationSkipped:
      'The cancellation could not be posted: the Noticeboard is switched off. It can be posted once it is back on.',
    postCancellation: 'Post the cancellation',
  },
  tasks: {
    heading: 'Tasks',
    progress: '{done} of {total} tasks done',
    overdue: '{count} overdue',
    add: 'Add a task',
    remove: 'Remove',
  },
  account: {
    heading: 'Event account',
    income: 'Income',
    spending: 'Spending',
    balance: 'Balance',
    receipts: 'Receipts',
    awaiting: '{count} awaiting approval in the Treasury.',
    budgetLines: 'Budget lines',
    change: 'Change',
    remove: 'Remove',
    addLine: 'Add a budget line',
    lineName: 'Budget line',
    lineAmount: 'Amount (£)',
    openInTreasury: 'Open the account in the Treasury',
  },
  files: {
    heading: 'Event files',
    sections: { Documents: 'Documents', Media: 'Media' },
    section: 'Section',
    file: 'File',
    add: 'Add the file',
    remove: 'Remove',
  },
  volunteers: { heading: 'Volunteers', comingSoon: 'Coming soon' },
  close: {
    heading: 'Close the event',
    overspent:
      'This event is overspent by {amount}. Closing takes {amount} from the chosen branch account to bring it to zero.',
    returned: 'Closing returns the balance of {amount} to the chosen branch account.',
    explain:
      'The post-event report and every event file are filed to the archive, and the event and its tasks are locked.',
    account: 'Branch account',
    confirm: 'Close the event',
  },
  templates: {
    heading: 'Event templates',
    none: 'There are no templates yet.',
    add: 'New template',
    name: 'Template name',
    tasks: 'Default tasks',
    taskTitle: 'Task',
    taskDescription: 'Description (optional)',
    daysBefore: 'Days before the first day',
    removeRow: 'Remove',
    addTask: 'Add a task',
    budgetLines: 'Default budget lines',
    lineName: 'Budget line',
    lineAmount: 'Amount (£)',
    addLine: 'Add a budget line',
    retired: 'Retired',
    summary: '{tasks} tasks, {lines} budget lines',
    change: 'Change',
    retire: 'Retire',
    restore: 'Bring back',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its events are read-only.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
    'request.invalid': 'Check the details and try again.',
    'pdf.not-available': 'PDFs are not available here. They work on the preview site.',
    'files.type-not-allowed': 'This file type is not allowed here.',
    'files.too-large': 'This file is larger than the limit.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'files.upload-failed': 'The upload did not finish. Try again.',
    'files.not-uploaded': 'The upload did not finish. Try again.',
    'files.photo-not-readable': 'This photo could not be read.',
    'task-tracker.owner-not-an-officer': 'Choose one of the unit’s current officers as the owner.',
    'task-tracker.task-not-found': 'This task does not exist.',
    'treasury.not-an-open-branch-account': 'Choose one of the unit’s open branch accounts.',
    'treasury.account-closed': 'The event account is already closed.',
    'event-organiser.stale':
      'Someone else changed this event. Reload the page to see their change.',
    'event-organiser.locked': 'This event is closed and locked.',
    'event-organiser.event-not-found': 'This event does not exist.',
    'event-organiser.template-not-found': 'This template does not exist.',
    'event-organiser.type-not-in-list': 'Choose a type from the list.',
    'event-organiser.lead-not-an-officer':
      'Choose one of the unit’s current officers as the lead officer.',
    'event-organiser.own-event': 'You created this event, so a second officer must approve it.',
    'event-organiser.not-a-draft': 'Only a draft event can be approved.',
    'event-organiser.status-move-not-allowed': 'This status move is not allowed.',
    'event-organiser.not-cancellable': 'This event can no longer be cancelled.',
    'event-organiser.not-cancelled': 'This event is not cancelled.',
    'event-organiser.nothing-to-post': 'There is no cancellation to post.',
    'event-organiser.not-publishable': 'This event cannot be published now.',
    'event-organiser.budget-fixed': 'The budget is fixed once the event is approved.',
    'event-organiser.budget-line-not-found': 'This budget line does not exist.',
    'event-organiser.budget-line-tagged':
      'Money is recorded against this budget line, so it cannot be removed.',
    'event-organiser.use-not-in-section': 'This kind of file does not go in that section.',
    'event-organiser.file-not-found': 'This file does not exist.',
    'event-organiser.report-not-ready':
      'The post-event report is available once the event is completed.',
    'event-organiser.not-closable': 'Only a completed or cancelled event can be closed.',
    'event-organiser.amount-invalid':
      'Write each amount in pounds, such as 150 or 150.50, and each number of days as a whole number.',
  },
  statuses: {
    Draft: 'Draft',
    Approved: 'Approved',
    'In preparation': 'In preparation',
    Ready: 'Ready',
    Completed: 'Completed',
    Cancelled: 'Cancelled',
    Closed: 'Closed',
  },
  reportPdf: {
    title: 'Post-event report: {name}',
    titleCancelled: 'Post-event report: {name} (cancelled)',
    dates: 'Date: {dates}',
    type: 'Type: {type}',
    lead: 'Lead officer: {name}',
    cancelReason: 'Cancelled: {reason}',
    tasksHeading: 'Tasks',
    tasksSummary: '{done} of {total} tasks done',
    taskHeadings: { task: 'Task', status: 'Status' },
    budgetHeading: 'Budget against actual',
    budgetHeadings: {
      line: 'Budget line',
      budget: 'Budget',
      income: 'Income',
      spending: 'Spending',
    },
    unallocated: 'Unallocated',
    totals: 'Totals',
    balance: 'Final balance',
  },
};
