/** Brief 14 C2 and D-067: handovers in the register. */
export const handoversText = {
  mine: 'Handovers you take part in',
  noHandovers: 'No handovers.',
  summary: '{role}: {outgoing} to {incoming}',
  statuses: { open: 'Open', confirming: 'Being confirmed', complete: 'Complete' },
  setUpHeading: 'Set up a handover',
  outgoing: 'Outgoing officer',
  incoming: 'Incoming officer',
  choosePerson: 'Choose an officer',
  setUp: 'Set up handover',
  confirmedBy: '{name} confirmed on {date}',
  notYetConfirmed: '{name} has not confirmed yet',
  checklist: 'Checklist',
  noItems: 'The checklist is empty.',
  removeItem: 'Remove {name}',
  addItem: 'Add item',
  confirmExplanation:
    'Confirm the whole handover once you are satisfied. The first confirmation fixes the checklist; when both officers have confirmed, the handover is complete and locked.',
  confirmChecked: 'I have checked the checklist.',
  confirm: 'Confirm handover',
  refusals: {
    'handovers.checklist-fixed': 'Confirmation has started, so the checklist can no longer change.',
    'handovers.already-confirmed': 'You have already confirmed this handover.',
    'handovers.not-a-participant': 'Only the two officers named on a handover can confirm it.',
    'handovers.same-person': 'The outgoing and incoming officers must be different people.',
    'handovers.not-officers-of-unit': 'Both officers must hold, or have held, a term in this unit.',
    'handovers.item-not-found': 'This item no longer exists.',
    'handovers.not-found': 'This handover no longer exists.',
    'roles.not-found': 'This role cannot be used in this unit.',
    'branches.inactive': 'This branch is inactive, so its register is read-only.',
    'request.invalid': 'Check the fields and try again.',
  },
};
