/** Brief 16 A1 to A3 and D-103, D-104: templates and guides. */
export const libraryResourcesText = {
  headings: { template: 'Templates', guide: 'Guides' },
  explanation: {
    template: 'Forms, sign-in sheets, flyer and poster designs, and other ready-to-use files.',
    guide: 'Role handbooks, procedures and how-to guides for officers.',
  },
  none: 'Nothing here yet.',
  add: { template: 'Add a template', guide: 'Add a guide' },
  file: 'File',
  title: 'Title',
  description: 'Description (optional)',
  language: 'Language of the file',
  languages: { en: 'English', ar: 'Arabic' },
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Change details',
  replace: 'Replace file',
  replaceExplanation: 'The new file is shown from now on; the old one is kept.',
  download: 'Download',
  retire: 'Retire',
  restore: 'Bring back',
  national: 'General Council',
  retired: 'Retired',
  refusals: {
    'permission.denied': 'You may not do this.',
    'resources-library.stale': 'Someone else changed this. Reload the page to see their change.',
    'resources-library.resource-not-found': 'This no longer exists.',
    'resources-library.already-retired': 'This is already retired.',
    'resources-library.not-retired': 'This is not retired.',
    'branches.inactive': 'This branch is inactive, so its library is read-only.',
    'files.type-not-allowed': 'This file type is not allowed for documents.',
    'files.too-large': 'This file is larger than the limit for documents.',
    'files.storage-not-configured': 'File storage is not set up yet.',
    'files.upload-failed': 'The upload did not finish. Try again.',
    'files.not-uploaded': 'The upload did not finish. Try again.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
  },
};
