export const meetingRecorderText = {
  name: 'Meeting recorder',
  capabilities: {
    'meeting-recorder.meetings.read': 'See meetings',
    'meeting-recorder.meetings.manage': 'Manage meetings',
  },
  settings: {
    'meeting-recorder.minutes_autosave_seconds': 'Minutes autosave interval (seconds)',
  },
  list: { heading: 'Meetings', none: 'There are no meetings yet.', add: 'New meeting' },
  form: {
    type: 'Type',
    date: 'Date',
    startTime: 'Start time',
    place: 'Place (or give an online link)',
    onlineLink: 'Online link (or give a place)',
    chair: 'Chair',
    secretary: 'Secretary',
    save: 'Save',
    cancel: 'Cancel',
  },
  details: { when: 'When', cancelled: 'Cancelled: {reason}', edit: 'Change details' },
  status: {
    hold: 'The meeting has started: mark it held',
    log: 'Log the report',
    download: 'Download the report',
    cancel: 'Cancel the meeting',
    cancelWarning: 'A cancelled meeting leaves the Calendar and cannot be brought back.',
    reason: 'Reason for cancelling',
    confirmCancel: 'Cancel the meeting',
  },
  attendees: {
    heading: 'Attendees',
    mark: 'Attendance of',
    notMarked: 'Not marked',
    remove: 'Remove',
    add: 'Add attendees',
    addChosen: 'Add the chosen officers',
  },
  agenda: {
    heading: 'Agenda',
    up: 'Move up',
    down: 'Move down',
    change: 'Change',
    remove: 'Remove',
    add: 'Add an item',
    addRaised: 'Add a point raised in the meeting',
    title: 'Item',
    note: 'Note (optional)',
  },
  minutes: {
    heading: 'Minutes',
    theirs: 'Someone else saved this comment as:',
    saved: 'Saved',
    save: 'Save',
  },
  outcome: {
    kind: 'Concluded with',
    decision: 'A decision',
    vote: 'A vote',
    for: 'For',
    against: 'Against',
    abstain: 'Abstaining',
    result: 'Result',
    decisionText: 'Decision',
    save: 'Save the outcome',
  },
  targets: {
    notSent: {
      calendar: 'Not yet in the Calendar.',
      'meeting-scheduled': 'The "meeting scheduled" notice has not been posted.',
      'meeting-held': 'The "meeting has taken place" notice has not been posted.',
    },
    skipped: {
      calendar: 'Not in the Calendar: it was switched off. It can be added once it is back on.',
      'meeting-scheduled':
        'The "meeting scheduled" notice was not posted: the Noticeboard was switched off. It can be posted once it is back on.',
      'meeting-held':
        'The "meeting has taken place" notice was not posted: the Noticeboard was switched off. It can be posted once it is back on.',
    },
    send: {
      calendar: 'Add to the Calendar',
      'meeting-scheduled': 'Post "meeting scheduled"',
      'meeting-held': 'Post "meeting has taken place"',
    },
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its meetings are read-only.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
    'request.invalid': 'Check the details and try again.',
    'pdf.not-available': 'PDFs are not available here. They work on the preview site.',
    'meeting-recorder.stale': 'Someone else changed this. Reload the page to see their change.',
    'meeting-recorder.locked': 'This meeting is locked.',
    'meeting-recorder.meeting-not-found': 'This meeting does not exist.',
    'meeting-recorder.type-not-in-list': 'Choose a type from the list.',
    'meeting-recorder.not-an-officer': 'Choose from the unit’s current officers.',
    'meeting-recorder.wrong-status': 'This cannot be done at this stage of the meeting.',
    'meeting-recorder.not-yet': 'The meeting can be marked held from its date.',
    'meeting-recorder.chair-or-secretary': 'The chair and the secretary always attend.',
    'meeting-recorder.has-comments':
      'This officer has comments in the minutes, so they stay marked present.',
    'meeting-recorder.attendee-not-found': 'This officer is not an attendee.',
    'meeting-recorder.item-not-found': 'This agenda item does not exist.',
    'meeting-recorder.original-agenda-fixed':
      'The original agenda is fixed once the meeting is held.',
    'meeting-recorder.agenda-changed': 'The agenda has changed. Reload the page and try again.',
    'meeting-recorder.not-present': 'Comments are recorded for officers marked present.',
    'meeting-recorder.too-many-votes': 'The votes add up to more than the officers present.',
    'meeting-recorder.count-invalid': 'Write each number of votes as a whole number.',
    'meeting-recorder.attendance-unmarked': 'Mark every attendee before logging the report.',
    'meeting-recorder.item-without-outcome':
      'Give every agenda item a vote or a decision before logging the report.',
    'meeting-recorder.nothing-to-send': 'There is nothing to send.',
    'meeting-recorder.service-off': 'That service is switched off.',
    'meeting-recorder.report-not-logged': 'The report has not been logged yet.',
  },
  statuses: {
    Scheduled: 'Scheduled',
    Held: 'Held',
    'Report logged': 'Report logged',
    Cancelled: 'Cancelled',
  },
  attendance: {
    Present: 'Present',
    Apologies: 'Apologies',
    'Did not attend': 'Did not attend',
  },
  reportPdf: {
    title: 'Meeting report: {type}',
    when: 'Date: {date}, {time}',
    place: 'Place: {place}',
    link: 'Online: {link}',
    chair: 'Chair: {name}',
    secretary: 'Secretary: {name}',
    attendance: 'Attendance',
    notMarked: 'Not marked',
    originalAgenda: 'Agenda',
    updatedAgenda: 'Agenda as updated in the meeting',
    raised: '{title} (raised in meeting)',
    recordedFor: 'Recorded for {officer} by {recorder}',
    minutes: 'Minutes',
    vote: 'Vote: {for} for, {against} against, {abstain} abstaining. Result: {result}',
    decision: 'Decision: {decision}',
  },
};
