/** Brief 25 Stage D: the Administration panel's operations screens (D-217). */
export const operationsText = {
  health: {
    intro:
      'The last run and outcome of every scheduled job, phone alerts that were never delivered, and storage used per unit.',
    jobs: 'Scheduled jobs',
    jobLine: '{job} ({schedule}): {outcome}',
    lastRun: 'last run {date}',
    never: 'not run yet',
    success: 'worked',
    failure: 'failed ({code})',
    runAgain: 'Run {job} again',
    pushFailures: 'Phone alerts not delivered: {count}',
    pushLine: '{date}: {kind} ({status})',
    storage: 'Storage used',
    unitStorage: '{unit}: {files} files, {size}',
  },
  audit: {
    intro:
      'Every recorded action. Before and after values are shown only for the Administration panel’s own changes, never for content.',
    person: 'Person',
    anyone: 'Anyone',
    service: 'Service',
    allServices: 'Every service',
    entityType: 'Kind of record (optional)',
    entityId: 'Record (optional)',
    from: 'From',
    to: 'To',
    search: 'Search',
    exportCsv: 'Export as CSV',
    none: 'Nothing matches.',
    entry: '{date}: {name}, {action}, {entityType} {entityId}',
    values: 'Before: {before}. After: {after}.',
    page: 'Page {page} of {pages}',
    previous: 'Previous page',
    next: 'Next page',
  },
  backups: {
    intro:
      'The database is backed up every night and kept for the backup retention. There is no restore button: restoring follows the written procedure in docs/operations.md.',
    now: 'Back up now',
    taking: 'Backing up…',
    none: 'No backups yet.',
    line: '{date}: {size}',
  },
  dataImport: {
    intro:
      'Import units, people with their current and past terms, and branch accounts from CSV files in the seed files’ format. Check first: nothing is written until you import. What is already there is left alone, nobody is invited, and opening balances are entered by each treasurer in the Treasury.',
    units: 'units.csv (optional)',
    people: 'people.csv (optional)',
    accounts: 'accounts.csv (optional)',
    check: 'Check the files',
    checking: 'Checking…',
    run: 'Import',
    running: 'Importing…',
    problems: 'Problems to fix first',
    ready: 'Ready to import:',
    unitsLine: 'Units: {added} to add, {present} already there',
    peopleLine: 'People: {added} to add, {present} already there',
    termsLine: 'Terms: {added} to add, {present} already there',
    accountsLine: 'Branch accounts: {added} to add, {present} already there',
    imported: 'Imported.',
  },
  files: {
    intro: 'Storage used per unit, and files kept in storage with no record.',
    storage: 'Storage used',
    orphans: 'Files with no record: {count} ({size})',
    orphanLine: '{date}: {key} ({size})',
    age: 'The nightly clean-up removes them once they are older than {days} days.',
    ageUnset: 'The orphan file age is not set, so the clean-up removes nothing yet.',
  },
  maintenance: {
    intro:
      'Read-only mode stops every change across the portal and shows a banner, while people can still read.',
    on: 'The portal is read-only.',
    off: 'The portal is working normally.',
    turnOn: 'Put the portal into read-only mode',
    turnOff: 'Take the portal out of read-only mode',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'setting.not-configured': 'This has not been set up yet. Set it on the set-up checklist.',
    'request.invalid': 'Check the details and try again.',
    'maintenance-mode.read-only': 'The portal is read-only while in maintenance mode.',
    'system-health.job-not-found': 'There is no such scheduled job.',
  },
};
