/** Brief 14: the Committee register pages in the portal. */
export const registerText = {
  noRegister: 'You have no register to open.',
  unit: 'Unit',
  inactive: 'This branch is inactive. Its register is read-only.',
  tabs: {
    officers: 'Officers',
    'past-officers': 'Past officers',
    roles: 'Roles',
    elections: 'Elections',
    handovers: 'Handovers',
  },
  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  role: 'Role',
  chooseRole: 'Choose a role',
  startDate: 'Start date',
  endDate: 'End date',
  endDateOptional: 'End date (if known)',
  save: 'Save',
  cancel: 'Cancel',
  from: 'from {start}',
  fromTo: '{start} to {end}',
  endingSoon: 'Ending soon',
  windowNotSet: 'Terms ending soon are not highlighted: the window has not been set.',
  noOfficers: 'No officers yet.',
  noPastOfficers: 'No past officers yet.',
  addOfficer: 'Add an officer',
  correctDetails: 'Correct name or phone',
  endTerm: 'End term',
  added: {
    sent: 'The officer was added and invited to sign in.',
    failed:
      'The officer was added, but the invitation could not be sent. Resend it from Officer accounts.',
    'not-needed': 'The officer was added. They already have an account or an invitation.',
  },
  updated: 'The details were corrected.',
  ended: 'The term was ended.',
  endedAndLocked: 'The term was ended, and their account was locked: it was their last term.',
  refusals: {
    'officers.already-holds-role': 'This person already holds this role in this unit.',
    'roles.not-found': 'This role cannot be used in this unit.',
    'terms.already-ended': 'This term has already ended.',
    'terms.end-before-start': 'A term cannot end before it starts.',
    'terms.not-found': 'This term no longer exists.',
    'branches.inactive': 'This branch is inactive, so its register is read-only.',
    'setting.not-configured':
      'This waits for the data administrator: the language new officers start with is not set.',
    'request.invalid': 'Check the fields: an end date must come after the start date.',
  },
};
