/** Brief 25 C1: the service settings screen, and the setting editor it shares. */
export const serviceSettingsText = {
  intro:
    'Every setting, by service. A setting has no value until one is entered here; until then, what depends on it waits. Every change is kept and can be restored.',
  required: 'Required',
  notConfigured: 'Not set',
  none: 'None',
  yes: 'Yes',
  no: 'No',
  choose: 'Choose',
  save: 'Save',
  cancel: 'Cancel',
  change: 'Change',
  changeSetting: 'Change {setting}',
  cannotEnterHere: 'This setting cannot be entered on screen.',
  setOnBranding: 'Set on the Branding and letterhead screen.',
  referenceFormatHint:
    'Use {unit_code}, {year} and {number}. {number:3} writes the number with at least three digits, such as 007. For example: {unit_code}/OUT/{year}/{number:3}',
  referenceFormatProblems: {
    empty: 'Enter a format.',
    'unknown-placeholder': 'Only {unit_code}, {year} and {number} can be used in braces.',
    'stray-brace': 'A brace is not closed or not opened.',
    'no-number': 'The format must contain {number}.',
    'number-twice': 'The format can contain {number} only once.',
    'no-year': 'The format must contain {year}, because the numbers start again each year.',
  },
  portalWide: 'Portal-wide',
  overrides: 'Unit overrides',
  noOverrides: 'No unit has its own value.',
  unit: 'Unit',
  chooseUnit: 'Choose a unit',
  addOverride: 'Give a unit its own value',
  removeOverride: 'Remove the override for {unit}',
  history: 'History',
  showHistory: 'Show history of {setting}',
  noHistory: 'No changes yet.',
  historyEntry: '{date}, {scope}, by {name}: {value}',
  overrideRemoved: 'override removed',
  restore: 'Restore this value',
  refusals: {
    'service-settings.not-registered': 'This setting no longer exists.',
    'service-settings.no-unit-override': 'This setting has one value for the whole portal.',
    'service-settings.no-override': 'This unit has no value of its own.',
    'service-settings.history-not-found': 'This change no longer exists.',
    'branches.not-found': 'This unit no longer exists.',
    'request.invalid': 'This value is not allowed for this setting.',
  },
};
