export const taskTrackerText = {
  name: 'Task tracker',
  capabilities: {
    'task-tracker.tasks.read': 'Read the action list',
    'task-tracker.tasks.manage': 'Manage tasks',
  },
  settings: {
    'task-tracker.due_soon_window_days': 'Due soon window (days)',
    'task-tracker.reminder_days_before': 'Reminder (days before the due date)',
  },
  sections: { label: 'Task tracker sections', mine: 'My tasks', actionList: 'Action list' },
  statuses: {
    'To do': 'To do',
    'In progress': 'In progress',
    Done: 'Done',
    Cancelled: 'Cancelled',
  },
  mine: { heading: 'My tasks', none: 'You have no tasks.' },
  actionList: {
    heading: 'Action list',
    none: 'No tasks match.',
    filters: 'Filters',
    owner: 'Owner',
    status: 'Status',
    any: 'Any',
    apply: 'Show',
  },
  flags: { dueSoon: 'Due soon', overdue: 'Overdue' },
  due: 'Due {date}',
  ownedBy: 'Owner: {name}',
  eventTask: 'Event task',
  add: 'Add a task',
  edit: 'Change',
  form: {
    title: 'Title',
    description: 'Description (optional)',
    owner: 'Owner',
    dueDate: 'Due date',
    status: 'Status',
    save: 'Save',
    cancel: 'Cancel',
  },
  statusLabel: 'Status of {title}',
  history: {
    show: 'History',
    created: 'Created by {name} on {date}',
    changed: 'Changed by {name} on {date}',
    change: '{field}: {before} → {after}',
    fields: {
      title: 'Title',
      description: 'Description',
      ownerPersonId: 'Owner',
      dueDate: 'Due date',
      status: 'Status',
    },
    empty: '(none)',
  },
  refusals: {
    'permission.denied': 'You may not do this.',
    'branches.inactive': 'This branch is inactive, so its tasks are read-only.',
    'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
    'request.invalid': 'Check the details and try again.',
    'task-tracker.task-not-found': 'This task does not exist.',
    'task-tracker.owner-not-an-officer': 'Choose one of the unit’s current officers as the owner.',
    'task-tracker.stale': 'Someone else changed this task. Reload the page to see their change.',
  },
};
