/** Brief 17 B1 to B6: entries, receipts and corrections. */
export const treasuryEntriesText = {
  heading: 'Entries',
  none: 'No entries in this period.',
  record: { credit: 'Record a credit', debit: 'Record a debit', transfer: 'Record a transfer' },
  types: {
    'opening-balance': 'Opening balance',
    credit: 'Credit',
    debit: 'Debit',
    transfer: 'Transfer',
  },
  transferTo: 'Transfer to {account}',
  transferFrom: 'Transfer from {account}',
  approvalStatuses: {
    'Awaiting approval': 'Awaiting approval',
    Approved: 'Approved',
    Declined: 'Declined',
  },
  account: 'Account',
  toAccount: 'To account',
  amount: 'Amount (£)',
  date: 'Date',
  source: 'Source',
  paidTo: 'Paid to',
  description: 'Description',
  budgetLine: 'Budget line (optional)',
  receipts: 'Receipt photos',
  receiptsHint: 'Take a photo with your camera, or choose one.',
  takePhoto: 'Take photo',
  choosePhoto: 'Choose photo',
  photosChosen: '{count} photo(s) ready',
  save: 'Save',
  done: 'Done',
  cancel: 'Cancel',
  amountInvalid: 'Write the amount in pounds, such as 150 or 20.50.',
  willGoBelowZero: 'This takes {account} below zero. It will be saved, with a warning.',
  enteredBy: 'Entered by {name} on {date}',
  decidedBy: '{status} by {name} on {date}',
  declineReason: 'Reason: {reason}',
  reversalOf: 'Reverses an earlier entry',
  reversedBy: 'Reversed by a later entry',
  noReceipt: 'No receipt',
  addReceipt: 'Add receipt',
  download: 'Receipt {number}',
  correct: 'Correct',
  correctExplanation:
    'This records a reversing entry, dated today, that undoes this one. Then record the right entry as a new one.',
  correctNote: 'Why (optional)',
  confirmCorrect: 'Record reversing entry',
  period: { from: 'From', to: 'To', show: 'Show' },
  warnings: {
    'below-zero': '{account} is now below zero: {balance}.',
    'no-receipt': 'Saved without a receipt. You can add one later.',
  },
  saved: {
    'Not needed': 'Saved.',
    'Awaiting approval':
      'Saved. It is above the threshold, so it waits for a second officer to approve it.',
  },
};
