/** The Treasury's refusals, in words, with the numbers they state. */
export const treasuryRefusalsText = {
  'permission.denied': 'You may not do this.',
  'branches.inactive': 'This branch is inactive, so its Treasury is read-only.',
  'setting.not-configured': 'This has not been set up yet. Please ask your administrator.',
  'pdf.not-available': 'PDFs are not available here. They work on the preview site.',
  'request.invalid': 'Check the details and try again.',
  'treasury.account-not-found': 'This account does not exist.',
  'treasury.account-closed': 'This account is closed, so it takes no new entries.',
  'treasury.not-zero':
    'This account can close only at a zero balance with nothing awaiting approval.',
  'treasury.event-account-by-event-organiser': 'Event accounts are closed by the Event organiser.',
  'treasury.future-date': 'An entry cannot be dated in the future.',
  'treasury.closed-year': 'That date is in a closed financial year, whose entries are locked.',
  'treasury.receipt-required': 'A receipt photo is required for this.',
  'treasury.budget-line-not-of-account': 'Choose a budget line of this event account.',
  'treasury.entry-exists': 'This entry has already been saved.',
  'treasury.entry-not-found': 'This entry does not exist.',
  'treasury.receipt-not-found': 'This receipt does not exist.',
  'treasury.not-awaiting': 'This is no longer awaiting approval.',
  'treasury.self-approval': 'You entered this, so a second officer must decide it.',
  'treasury.reason-required': 'Give a reason for declining.',
  'treasury.already-reversed': 'This entry has already been reversed.',
  'treasury.reversal-not-reversed': 'A reversing entry cannot itself be reversed.',
  'treasury.not-counted': 'Only an entry that counts can be reversed.',
  'treasury.statement-already-filed': 'This statement has already been filed.',
  'treasury.not-a-year-start': 'That is not the start of a financial year.',
  'treasury.year-closed': 'This year is already closed.',
  'treasury.year-not-ended': 'This year has not ended yet.',
  'treasury.earlier-year-open': 'Close the earlier financial year first.',
  'treasury.awaiting-in-year': '{awaiting} dated in this year await approval. Decide them first.',
  'files.type-not-allowed': 'This file type is not allowed for receipt photos.',
  'files.too-large': 'This photo is larger than the limit for receipt photos.',
  'files.storage-not-configured': 'File storage is not set up yet.',
  'files.upload-failed': 'The upload did not finish. Try again.',
  'files.not-uploaded': 'The upload did not finish. Try again.',
};
