/** Brief 16 B1 and D-098, D-105 to D-107: the venue directory. */
export const venuesText = {
  heading: 'Venues',
  none: 'No venues yet.',
  add: 'Add a venue',
  name: 'Name',
  address: 'Address',
  capacity: 'Capacity',
  facilities: 'Facilities',
  contactName: 'Contact person',
  contactPhone: 'Contact phone',
  contactEmail: 'Contact email',
  typicalCost: 'Typical cost (£)',
  typicalCostNote: 'What the cost covers',
  optional: '{label} (optional)',
  costInvalid: 'Write the cost in pounds, such as 150 or 150.50.',
  people: '{count} people',
  save: 'Save',
  cancel: 'Cancel',
  edit: 'Change details',
  retire: 'Retire',
  restore: 'Bring back',
  national: 'General Council',
  retired: 'Retired',
  notes: 'Notes from past use',
  noNotes: 'No notes yet.',
  noteBy: '{name}, {date}',
  noteOn: '{date}',
  newNote: 'Add a note',
  addNote: 'Add note',
  retireNote: 'Retire note',
  refusals: {
    'permission.denied': 'You may not do this.',
    'resources-library.stale':
      'Someone else changed this venue. Reload the page to see their change.',
    'resources-library.venue-not-found': 'This venue no longer exists.',
    'resources-library.venue-note-not-found': 'This note is no longer showing.',
    'resources-library.already-retired': 'This venue is already retired.',
    'resources-library.not-retired': 'This venue is not retired.',
    'branches.inactive': 'This branch is inactive, so its library is read-only.',
  },
};
