import type { TextShape } from '../text-shape';
import type { achievementsAndReportsText as english } from '../en/achievements-and-reports';

export const achievementsAndReportsText: TextShape<typeof english> = {
  name: 'الإنجازات والتقارير',
  capabilities: {
    'achievements-and-reports.achievements.read': 'الاطلاع على الإنجازات',
    'achievements-and-reports.achievements.record': 'تسجيل الإنجازات',
    'achievements-and-reports.annual-report.manage': 'إدارة التقرير السنوي',
  },
  settings: {
    'achievements-and-reports.report_year_start': 'بداية سنة التقرير السنوي',
  },
  tabs: { timeline: 'السجل الزمني', contributions: 'المساهمات', reports: 'التقارير السنوية' },
  timeline: {
    scopes: { unit: 'هذه الوحدة', national: 'المجلس العام', all: 'كل الفروع' },
    none: 'لم يُسجَّل أي إنجاز بعد.',
    record: 'تسجيل إنجاز',
    officers: 'الأعضاء المشاركون: {names}',
    withdrawn: 'مسحوب',
    locked: 'مقفل: التقرير السنوي لسنته قد اعتُمد.',
    change: 'تعديل',
    withdraw: 'سحب',
    restore: 'إعادة',
    photos: 'الصور',
    viewPhoto: 'عرض {name}',
    removePhoto: 'إزالة {name}',
    addPhoto: 'إضافة صورة',
    adding: 'جارٍ الإضافة…',
  },
  form: {
    heading: 'تسجيل إنجاز',
    changeHeading: 'تعديل الإنجاز',
    title: 'العنوان',
    date: 'التاريخ',
    category: 'الفئة',
    description: 'الوصف',
    officers: 'الأعضاء المشاركون',
    officersHint: 'كل من خدم في هذه الوحدة، ومنهم الأعضاء السابقون.',
    save: 'حفظ',
    cancel: 'إلغاء',
    choose: 'اختر…',
  },
  contributions: {
    heading: 'مساهمات الأعضاء',
    none: 'لم يخدم أحد هنا بعد.',
    roles: 'المناصب التي شغلها',
    term: '{role}، {unit}: من {start} إلى {end}',
    toDate: 'الآن',
    achievements: 'الإنجازات',
    noAchievements: 'لا إنجازات منسوبة بعد.',
    achievement: '{date}: {title} ({category})',
  },
  reports: {
    heading: 'التقارير السنوية',
    none: 'لا توجد تقارير سنوية بعد.',
    start: 'بدء تقرير {year}',
    statuses: { Draft: 'مسودة', Finalised: 'معتمد' },
    report: 'تقرير {year}',
    draftNote: 'تعرض المسودة أحدث الأرقام من السجلات. لا يُكتب هنا إلا الملخص.',
    summaryLabel: 'ملخص الفرع (اختياري)',
    saveSummary: 'حفظ الملخص',
    saved: 'حُفظ',
    finalise: 'اعتماد وقفل',
    finaliseConfirm:
      'هل تعتمد تقرير {year}؟ يُجمَّد محتواه ويُحفظ ملف PDF منه في الأرشيف، ولا يمكن تغييره أبدًا.',
    provisionalWarning: 'السنة المالية لم تُغلق بعد، لذا ستُعلَّم أرقام الخزينة بأنها مؤقتة.',
    confirm: 'نعم، اعتمده',
    cancel: 'إلغاء',
    finalising: 'جارٍ الاعتماد…',
    finalisedOn: 'اعتُمد في {date} بواسطة {name}',
    download: 'تنزيل ملف PDF',
  },
  reportPdf: {
    title: 'التقرير السنوي {year}: {unit}',
    period: 'من {start} إلى {end}',
    summary: 'الملخص',
    achievements: 'الإنجازات',
    events: 'الفعاليات المكتملة',
    meetings: 'الاجتماعات المنعقدة',
    treasury: 'الخزينة',
    officers: 'الأعضاء الحاليون',
    none: 'لا شيء.',
    notInUse: 'خدمة {service} غير مستخدمة في هذه الوحدة.',
    achievementLine: '{date}: {title} ({category}). {officers}',
    listSeparator: '، ',
    eventLine: '{date}: {name}',
    meetingLine: '{date}: {type}',
    officerLine: '{name}، {role}',
    provisional: 'مؤقت: السنة المالية لم تُغلق بعد.',
    treasuryYear: 'السنة المالية من {start} إلى {end}',
    startBalance: 'الرصيد في البداية: {amount}',
    openingBalances: 'الأرصدة الافتتاحية المُدخلة: {amount}',
    credits: 'الوارد: {amount}',
    debits: 'الصادر: {amount}',
    endBalance: 'الرصيد في النهاية: {amount}',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بهذا.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا إنجازاته للقراءة فقط.',
    'branches.not-found': 'هذه الوحدة غير موجودة.',
    'service.switched-off': 'خدمة الإنجازات والتقارير متوقفة لهذه الوحدة.',
    'setting.not-configured': 'لم يُضبط هذا بعد. يُرجى مراجعة المسؤول.',
    'request.invalid': 'تحقق من التفاصيل وحاول مرة أخرى.',
    'pdf.not-available': 'ملفات PDF غير متاحة هنا. إنها تعمل على موقع المعاينة.',
    'files.type-not-allowed': 'نوع الملف هذا غير مسموح به هنا.',
    'files.too-large': 'هذا الملف أكبر من الحد المسموح.',
    'files.storage-not-configured': 'لم يُضبط تخزين الملفات بعد.',
    'achievements-and-reports.stale': 'غيّر شخص آخر هذا. أعد تحميل الصفحة لترى التغيير.',
    'achievements-and-reports.locked': 'هذا مقفل: التقرير السنوي لسنته قد اعتُمد.',
    'achievements-and-reports.future-date': 'لا يمكن أن يكون التاريخ في المستقبل.',
    'achievements-and-reports.category-not-in-list': 'اختر فئة من القائمة.',
    'achievements-and-reports.not-an-officer': 'اختر أشخاصًا خدموا في هذه الوحدة.',
    'achievements-and-reports.achievement-not-found': 'هذا الإنجاز غير موجود.',
    'achievements-and-reports.already-withdrawn': 'هذا الإنجاز مسحوب بالفعل.',
    'achievements-and-reports.not-withdrawn': 'هذا الإنجاز غير مسحوب.',
    'achievements-and-reports.photo-not-found': 'هذه الصورة غير موجودة.',
    'achievements-and-reports.person-not-found': 'لم يخدم هذا الشخص هنا.',
    'achievements-and-reports.year-not-ended': 'لم تنتهِ هذه السنة بعد، فلا يمكن بدء تقريرها.',
    'achievements-and-reports.already-started': 'بدأ تقرير هذه السنة بالفعل.',
    'achievements-and-reports.report-not-found': 'هذا التقرير غير موجود.',
    'achievements-and-reports.report-not-finalised': 'لم يُعتمد هذا التقرير بعد.',
  },
};
