import type { TextShape } from '../text-shape';
import type { calendarText as english } from '../en/calendar';

export const calendarText: TextShape<typeof english> = {
  name: 'التقويم',
  capabilities: {
    'calendar.calendar.read': 'الاطلاع على التقويم',
    'calendar.community-dates.manage': 'إدارة المناسبات المجتمعية',
  },
  settings: {
    'calendar.feed_includes_all_branch_dates': 'رابط الهاتف يشمل المناسبات المجتمعية لكل الفروع',
  },
  views: { label: 'العرض', month: 'شهر', week: 'أسبوع', list: 'قائمة' },
  scope: { label: 'إظهار', branch: 'هذا الفرع', all: 'كل الفروع' },
  filters: {
    kinds: 'إظهار',
    branches: 'الفروع',
    meeting: 'الاجتماعات',
    event: 'الفعاليات',
    community: 'المناسبات المجتمعية',
  },
  previous: 'السابق',
  weekOf: 'الأسبوع الذي يبدأ في {date}',
  close: 'إغلاق',
  next: 'التالي',
  none: 'لا شيء في هذه الفترة.',
  kinds: { meeting: 'اجتماع', event: 'فعالية', community: 'مناسبة مجتمعية' },
  forAllBranches: 'لكل الفروع',
  retired: 'موقوفة',
  readOnly: 'تُعدَّل في خدمتها فقط',
  add: 'إضافة مناسبة مجتمعية',
  edit: 'تعديل',
  retire: 'إيقاف',
  restore: 'إعادة',
  form: {
    title: 'العنوان',
    startDate: 'التاريخ (اليوم الأول)',
    endDate: 'اليوم الأخير (لعدة أيام)',
    startTime: 'الوقت (اختياري)',
    description: 'الوصف (اختياري)',
    forAllBranches: 'لكل الفروع',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  clash: 'في هذا اليوم لدى الوحدة أيضًا: {items}. يمكنك الحفظ مع ذلك.',
  feed: {
    heading: 'تقويم الهاتف',
    explanation: 'اشترك مرة واحدة على هاتفك، فتظهر مواعيد البوابة في تقويم هاتفك وتبقى محدَّثة.',
    none: 'ليس لديك رابط لتقويم الهاتف بعد.',
    since: 'أُنشئ رابطك في {date}.',
    make: 'إنشاء رابط',
    remake: 'إنشاء رابط جديد (يتوقف الرابط القديم)',
    shownOnce: 'رابطك — انسخه الآن؛ لن يظهر إلا هذه المرة:',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فتقويمه للاطلاع فقط.',
    'setting.not-configured': 'لم يتم إعداد هذا بعد. يرجى التواصل مع المسؤول.',
    'request.invalid': 'راجع التفاصيل: لا يمكن أن يسبق اليومُ الأخير اليومَ الأول.',
    'calendar.all-branches-general-council-only': 'المجلس العام وحده يضيف مناسبات لكل الفروع.',
    'calendar.community-date-not-found': 'هذه المناسبة لم تعد موجودة.',
    'calendar.stale': 'عدّل شخص آخر هذه المناسبة. أعد تحميل الصفحة لترى تعديله.',
    'calendar.already-retired': 'هذه المناسبة موقوفة بالفعل.',
    'calendar.not-retired': 'هذه المناسبة غير موقوفة.',
  },
};
