import type { TextShape } from '../text-shape';
import type { communicationHubText as english } from '../en/communication-hub';

export const communicationHubText: TextShape<typeof english> = {
  name: 'مركز التواصل',
  capabilities: {
    'communication-hub.noticeboard.read': 'الاطلاع على لوحة الإعلانات',
    'communication-hub.noticeboard.manage': 'إدارة لوحة الإعلانات',
  },
  settings: {
    'communication-hub.alert_types_for_new_officers':
      'أنواع التنبيهات المفعّلة لأعضاء اللجان الجدد',
  },
  sections: { label: 'أقسام مركز التواصل', noticeboard: 'لوحة الإعلانات' },
  noticeboard: {
    heading: 'لوحة الإعلانات',
    none: 'لا توجد إعلانات بعد.',
    post: 'نشر إعلان',
    postedBy: 'نشره {name} في {date}',
    automatic: 'تلقائي',
    automaticKinds: {
      'event-published': 'نُشرت فعالية: {title}، {date}',
      'meeting-scheduled': 'حُدّد موعد اجتماع: {title}، {date}',
      'meeting-held': 'عُقد اجتماع: {title}، {date}',
    },
    retired: 'موقوف',
    edit: 'تعديل',
    retire: 'إيقاف',
    restore: 'إعادة',
  },
  noticeForm: {
    title: 'العنوان',
    body: 'النص',
    withVote: 'طرح هذا الإعلان للتصويت',
    question: 'السؤال',
    option: 'الخيار {number}',
    addOption: 'إضافة خيار',
    removeOption: 'حذف',
    closesOn: 'تاريخ الإغلاق (يُغلق التصويت بنهاية هذا اليوم)',
    eligibility: 'من يحق له التصويت',
    eligibilities: {
      unit: 'جميع أعضاء لجنة الوحدة',
      roles: 'أصحاب المناصب المختارة',
      named: 'أعضاء محددون بالاسم',
    },
    roles: 'المناصب',
    officers: 'الأعضاء',
    voteLocked:
      'صوّت أحدهم بالفعل، فلم يعد بالإمكان تعديل التصويت. ويمكن تأجيل تاريخ إغلاقه من الإعلان نفسه.',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  vote: {
    closesOn: 'يُغلق التصويت بنهاية {date}.',
    closed: 'أُغلق التصويت بنهاية {date}.',
    cast: 'صوّت',
    youVoted: 'صوّتَّ لـ: {option}.',
    notEligible: 'لست من المصوّتين في هذا التصويت.',
    resultsLater: 'تظهر النتائج عند إغلاق التصويت.',
    results: 'النتائج',
    count: 'عدد الأصوات: {count}',
    extend: 'تأجيل تاريخ الإغلاق',
    newClosesOn: 'تاريخ الإغلاق الجديد',
    extendSave: 'تأجيل',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بهذا.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فإن لوحة إعلاناته للاطلاع فقط.',
    'request.invalid': 'تحقق من التفاصيل: يحتاج التصويت إلى سؤال وخيارين مختلفين على الأقل.',
    'communication-hub.notice-not-found': 'هذا الإعلان لم يعد موجودًا.',
    'communication-hub.stale': 'عدّل شخص آخر هذا الإعلان. أعد تحميل الصفحة لترى التعديل.',
    'communication-hub.already-retired': 'هذا الإعلان موقوف بالفعل.',
    'communication-hub.not-retired': 'هذا الإعلان غير موقوف.',
    'communication-hub.automatic-post-unchanged': 'لا يمكن تعديل المنشور التلقائي.',
    'communication-hub.vote-locked': 'صوّت أحدهم بالفعل، فلم يعد بالإمكان تعديل التصويت.',
    'communication-hub.closing-date-past': 'لا يمكن أن يكون تاريخ الإغلاق في الماضي.',
    'communication-hub.no-eligible-voters': 'لن يتمكن أحد من التصويت: اختر مصوّتين آخرين.',
    'communication-hub.role-not-found': 'أحد المناصب المختارة لم يعد موجودًا.',
    'communication-hub.not-a-current-officer':
      'لا يُسمّى مصوّتًا إلا أعضاء اللجنة الحاليون في الوحدة.',
    'communication-hub.vote-not-found': 'هذا التصويت لم يعد موجودًا.',
    'communication-hub.vote-closed': 'أُغلق التصويت.',
    'communication-hub.not-eligible': 'لست من المصوّتين في هذا التصويت.',
    'communication-hub.already-voted': 'لقد صوّتَّ بالفعل، ولا يمكن تغيير الصوت.',
    'communication-hub.option-not-found': 'هذا الخيار ليس من خيارات هذا التصويت.',
    'communication-hub.closing-date-not-later':
      'يجب أن يكون تاريخ الإغلاق الجديد بعد التاريخ الحالي.',
  },
  alertTypes: {
    notices: 'الإعلانات الجديدة',
    votes: 'التصويتات',
    circulars: 'التعاميم الوطنية',
    replies: 'الردود',
    requests: 'الطلبات',
  },
};
