import type { TextShape } from '../text-shape';
import type { communicationHubText as english } from '../en/communication-hub';

export const communicationHubText: TextShape<typeof english> = {
  name: 'مركز التواصل',
  capabilities: {
    'communication-hub.noticeboard.read': 'الاطلاع على لوحة الإعلانات',
    'communication-hub.noticeboard.manage': 'إدارة لوحة الإعلانات',
    'communication-hub.circulars.send': 'إرسال التعاميم الوطنية',
  },
  settings: {
    'communication-hub.alert_types_for_new_officers':
      'أنواع التنبيهات المفعّلة لأعضاء اللجان الجدد',
  },
  sections: {
    label: 'أقسام مركز التواصل',
    noticeboard: 'لوحة الإعلانات',
    circulars: 'التعاميم الوطنية',
  },
  noticeboard: {
    heading: 'لوحة الإعلانات',
    none: 'لا توجد إعلانات بعد.',
    post: 'نشر إعلان',
    postedBy: 'نشره {name} في {date}',
    automatic: 'تلقائي',
    automaticKinds: {
      'event-published': 'نُشرت فعالية: {title}، {date}',
      'meeting-scheduled': 'حُدّد موعد اجتماع: {title}، {date}',
      'meeting-held': 'عُقد اجتماع: {title}، {date}',
    },
    retired: 'موقوف',
    edit: 'تعديل',
    retire: 'إيقاف',
    restore: 'إعادة',
  },
  noticeForm: {
    title: 'العنوان',
    body: 'النص',
    withVote: 'طرح هذا الإعلان للتصويت',
    question: 'السؤال',
    option: 'الخيار {number}',
    addOption: 'إضافة خيار',
    removeOption: 'حذف',
    closesOn: 'تاريخ الإغلاق (يُغلق التصويت بنهاية هذا اليوم)',
    eligibility: 'من يحق له التصويت',
    eligibilities: {
      unit: 'جميع أعضاء لجنة الوحدة',
      roles: 'أصحاب المناصب المختارة',
      named: 'أعضاء محددون بالاسم',
    },
    roles: 'المناصب',
    officers: 'الأعضاء',
    voteLocked:
      'صوّت أحدهم بالفعل، فلم يعد بالإمكان تعديل التصويت. ويمكن تأجيل تاريخ إغلاقه من الإعلان نفسه.',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  vote: {
    closesOn: 'يُغلق التصويت بنهاية {date}.',
    closed: 'أُغلق التصويت بنهاية {date}.',
    cast: 'صوّت',
    youVoted: 'صوّتَّ لـ: {option}.',
    notEligible: 'لست من المصوّتين في هذا التصويت.',
    resultsLater: 'تظهر النتائج عند إغلاق التصويت.',
    results: 'النتائج',
    count: 'عدد الأصوات: {count}',
    extend: 'تأجيل تاريخ الإغلاق',
    newClosesOn: 'تاريخ الإغلاق الجديد',
    extendSave: 'تأجيل',
  },
  circulars: {
    heading: 'التعاميم الوطنية',
    none: 'لا توجد تعاميم بعد.',
    sentOn: 'أُرسل في {date}',
    opened: 'فتحه فرعك في {date}',
    notOpened: 'لم يفتحه فرعك بعد',
    open: 'قراءة',
    close: 'إغلاق',
    send: 'إرسال تعميم',
    sentBy: 'أرسله {name} في {date}',
    toAll: 'إلى جميع الفروع',
    toChosen: 'إلى فروع مختارة',
    openedCount: 'فتحه {opened} من {total} فرعًا',
    branchOpened: 'فُتح في {date}',
    branchNotOpened: 'لم يُفتح بعد',
    form: {
      title: 'العنوان',
      body: 'النص',
      recipients: 'الإرسال إلى',
      allBranches: 'جميع الفروع',
      chosenBranches: 'فروع مختارة',
      branches: 'الفروع',
      save: 'إرسال',
      cancel: 'إلغاء',
      final: 'لا يمكن تعديل التعميم بعد إرساله.',
    },
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بهذا.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فإن لوحة إعلاناته للاطلاع فقط.',
    'request.invalid': 'تحقق من التفاصيل: يحتاج التصويت إلى سؤال وخيارين مختلفين على الأقل.',
    'communication-hub.notice-not-found': 'هذا الإعلان لم يعد موجودًا.',
    'communication-hub.stale': 'عدّل شخص آخر هذا الإعلان. أعد تحميل الصفحة لترى التعديل.',
    'communication-hub.already-retired': 'هذا الإعلان موقوف بالفعل.',
    'communication-hub.not-retired': 'هذا الإعلان غير موقوف.',
    'communication-hub.automatic-post-unchanged': 'لا يمكن تعديل المنشور التلقائي.',
    'communication-hub.vote-locked': 'صوّت أحدهم بالفعل، فلم يعد بالإمكان تعديل التصويت.',
    'communication-hub.closing-date-past': 'لا يمكن أن يكون تاريخ الإغلاق في الماضي.',
    'communication-hub.no-eligible-voters': 'لن يتمكن أحد من التصويت: اختر مصوّتين آخرين.',
    'communication-hub.role-not-found': 'أحد المناصب المختارة لم يعد موجودًا.',
    'communication-hub.not-a-current-officer':
      'لا يُسمّى مصوّتًا إلا أعضاء اللجنة الحاليون في الوحدة.',
    'communication-hub.vote-not-found': 'هذا التصويت لم يعد موجودًا.',
    'communication-hub.vote-closed': 'أُغلق التصويت.',
    'communication-hub.not-eligible': 'لست من المصوّتين في هذا التصويت.',
    'communication-hub.already-voted': 'لقد صوّتَّ بالفعل، ولا يمكن تغيير الصوت.',
    'communication-hub.option-not-found': 'هذا الخيار ليس من خيارات هذا التصويت.',
    'communication-hub.closing-date-not-later':
      'يجب أن يكون تاريخ الإغلاق الجديد بعد التاريخ الحالي.',
    'communication-hub.general-council-only': 'المجلس العام وحده يرسل التعاميم الوطنية.',
    'communication-hub.branch-not-found': 'أحد الفروع المختارة لم يعد موجودًا.',
    'communication-hub.no-branches': 'لا توجد فروع للإرسال إليها.',
    'communication-hub.circular-not-found': 'لم يُرسل هذا التعميم إلى فرعك.',
  },
  alertTypes: {
    notices: 'الإعلانات الجديدة',
    votes: 'التصويتات',
    circulars: 'التعاميم الوطنية',
    replies: 'الردود',
    requests: 'الطلبات',
  },
};
