import type { TextShape } from '../text-shape';
import type { correspondenceAndLettersText as english } from '../en/correspondence-and-letters';

export const correspondenceAndLettersText: TextShape<typeof english> = {
  name: 'المراسلات والخطابات',
  capabilities: {
    'correspondence-and-letters.registers.read': 'الاطلاع على سجلّي الرسائل',
    'correspondence-and-letters.letters-out.write': 'كتابة الرسائل',
    'correspondence-and-letters.letters-in.record': 'تسجيل الرسائل الواردة',
  },
  settings: {
    'correspondence-and-letters.reference_format_out': 'صيغة الرقم المرجعي: الرسائل الصادرة',
    'correspondence-and-letters.reference_format_in': 'صيغة الرقم المرجعي: الرسائل الواردة',
  },
  tabs: { out: 'الرسائل الصادرة', in: 'الرسائل الواردة' },
  statuses: {
    Received: 'مستلمة',
    'Awaiting reply': 'بانتظار الرد',
    Replied: 'تم الرد',
    'No reply needed': 'لا تحتاج إلى رد',
  },
  lettersOut: {
    heading: 'الرسائل الصادرة',
    none: 'لم تُكتب أي رسالة بعد.',
    write: 'كتابة رسالة',
    reference: 'الرقم المرجعي',
    date: 'التاريخ',
    recipient: 'المرسَل إليه',
    subject: 'الموضوع',
    sentBy: 'أرسلها',
  },
  lettersIn: {
    heading: 'الرسائل الواردة',
    none: 'لم تُسجَّل أي رسالة بعد.',
    record: 'تسجيل رسالة واردة',
    reference: 'الرقم المرجعي',
    dateReceived: 'تاريخ الاستلام',
    sender: 'المرسِل',
    subject: 'الموضوع',
    handler: 'يتولاها',
    status: 'الحالة',
  },
  write: {
    heading: 'كتابة رسالة',
    template: 'النموذج',
    national: '{title} (المجلس العام)',
    recipientName: 'اسم المرسَل إليه',
    recipientAddress: 'عنوان المرسَل إليه (اختياري)',
    subject: 'الموضوع، للسجل',
    subjectHint: 'يُطبع على الرسالة فقط إذا كان لنموذجها سطر موضوع.',
    signAs: 'التوقيع بصفة',
    replyTo: 'ردًّا على (اختياري)',
    notAReply: 'ليست ردًّا',
    answerable: '{reference}: {sender}، {subject}',
    noTemplates: 'لا توجد بعد نماذج رسائل للكتابة منها.',
    noRoles: 'لا تشغل اليوم أي منصب في هذه الوحدة، فلا يمكنك توقيع رسالة فيها.',
    preview: 'معاينة',
    previewPdf: 'معاينة PDF',
    generate: 'إنشاء الرسالة',
    generating: 'جارٍ الإنشاء…',
    lockedNote: 'بعد إنشاء الرسالة تُرقَّم وتُحفظ، ولا يمكن تغييرها أبدًا.',
    choose: 'اختر…',
  },
  record: {
    heading: 'تسجيل رسالة واردة',
    file: 'مسح ضوئي أو صورة للرسالة',
    fileHint: 'الرسالة المكوّنة من عدة صفحات تُرفع ملف PDF واحدًا.',
    dateReceived: 'تاريخ الاستلام',
    sender: 'المرسِل',
    subject: 'الموضوع',
    handler: 'يتولاها',
    answers: 'ردًّا على رسالتنا (اختياري)',
    notAnAnswer: 'ليست ردًّا على إحدى رسائلنا',
    letterOut: '{reference}: {recipient}، {subject}',
    save: 'تسجيل الرسالة',
    saving: 'جارٍ التسجيل…',
    choose: 'اختر…',
  },
  letter: {
    download: 'تنزيل',
    recipientAddress: 'العنوان',
    signedBy: 'وقّعها {name}، {role}',
    handler: 'يتولاها',
    changeHandler: 'تغيير',
    saveLink: 'حفظ الربط',
    moveTo: 'وضع علامة: {status}',
    writeReply: 'كتابة رد',
    exchange: 'المراسلة كاملة',
    exchangeOut: 'صادرة {reference}، {date}: إلى {party}، {subject}',
    exchangeIn: 'واردة {reference}، {date}: من {party}، {subject}',
    thisLetter: '(هذه الرسالة)',
  },
  letterPdf: {
    reference: 'رقمنا المرجعي: {reference}',
    date: 'التاريخ: {date}',
    referenceToCome: '[يُعطى عند إنشاء الرسالة]',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بهذا.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا رسائله للقراءة فقط.',
    'branches.not-found': 'هذه الوحدة غير موجودة.',
    'service.switched-off': 'خدمة المراسلات متوقفة لهذه الوحدة.',
    'setting.not-configured':
      'لم يُضبط هذا بعد: صيغ الأرقام المرجعية أو الترويسة أو قواعد الملفات. يُرجى مراجعة المسؤول.',
    'request.invalid': 'تحقق من التفاصيل وحاول مرة أخرى.',
    'pdf.not-available': 'ملفات PDF غير متاحة هنا. إنها تعمل على موقع المعاينة.',
    'files.type-not-allowed': 'نوع الملف هذا غير مسموح به هنا.',
    'files.too-large': 'هذا الملف أكبر من الحد المسموح.',
    'files.storage-not-configured': 'لم يُضبط تخزين الملفات بعد.',
    'correspondence-and-letters.template-not-found': 'اختر أحد النماذج المعروضة.',
    'correspondence-and-letters.field-missing': 'املأ كل حقول الرسالة.',
    'correspondence-and-letters.not-your-role': 'وقّع بمنصب تشغله اليوم في هذه الوحدة.',
    'correspondence-and-letters.not-answerable':
      'لا يمكن الرد على تلك الرسالة: عليها علامة أنها لا تحتاج إلى رد.',
    'correspondence-and-letters.letter-not-found': 'هذه الرسالة غير موجودة.',
    'correspondence-and-letters.future-date': 'لا يمكن أن يكون تاريخ الاستلام في المستقبل.',
    'correspondence-and-letters.not-an-officer': 'اختر من أعضاء الوحدة الحاليين.',
    'correspondence-and-letters.wrong-status': 'لا يمكن نقل الرسالة إلى هذه الحالة.',
    'correspondence-and-letters.closed': 'هذه الرسالة مغلقة، فلم يعد ممكنًا تغيير من يتولاها.',
    'correspondence-and-letters.stale': 'غيّر شخص آخر هذه الرسالة. أعد تحميل الصفحة لترى التغيير.',
    'correspondence-and-letters.busy':
      'كانت رسائل أخرى تُرقَّم في اللحظة نفسها. يُرجى المحاولة مرة أخرى.',
  },
};
