import type { TextShape } from '../text-shape';
import type { documentsArchiveText as english } from '../en/documents-archive';

export const documentsArchiveText: TextShape<typeof english> = {
  name: 'أرشيف الوثائق',
  capabilities: {
    'documents-archive.documents.read': 'الاطلاع على الأرشيف',
    'documents-archive.documents.upload': 'الرفع إلى الأرشيف',
  },
  search: {
    heading: 'البحث في الأرشيف',
    title: 'العنوان',
    category: 'التصنيف',
    unit: 'الفرع',
    any: 'الكل',
    dateField: 'التاريخ',
    documentDate: 'تاريخ الوثيقة',
    filedDate: 'تاريخ الحفظ',
    from: 'من',
    to: 'إلى',
    submit: 'بحث',
    noResults: 'لا توجد وثائق مطابقة.',
  },
  document: {
    back: 'العودة إلى الأرشيف',
    automatic: 'حُفظت تلقائيًا؛ للاطلاع فقط',
    uploaded: 'مرفوعة',
    documentDate: 'تاريخ الوثيقة: {date}',
    filedOn: 'حُفظت في {date} بواسطة {name}',
    filedOnNoName: 'حُفظت في {date}',
    versions: 'الإصدارات',
    version: 'الإصدار {version}: {fileName}، أُضيف في {date}',
    download: 'تنزيل',
  },
  upload: {
    heading: 'رفع وثيقة',
    explanation: 'الوثائق الرسمية لأرشيف وحدتك، في تصنيف الحوكمة أو عام.',
    file: 'الملف',
    title: 'العنوان',
    description: 'الوصف',
    documentDate: 'تاريخ الوثيقة نفسها',
    category: 'التصنيف',
    submit: 'رفع',
    done: 'أصبحت الوثيقة في الأرشيف.',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'documents-archive.not-found': 'هذه الوثيقة غير موجودة، أو لا يحق لك الاطلاع عليها.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فأرشيفه للاطلاع فقط.',
    'files.type-not-allowed': 'نوع هذا الملف غير مسموح به للوثائق.',
    'files.too-large': 'حجم هذا الملف أكبر من الحد المسموح به للوثائق.',
    'files.storage-not-configured': 'لم يُجهَّز تخزين الملفات بعد.',
    'files.upload-failed': 'لم يكتمل الرفع. حاول مرة أخرى.',
    'files.not-uploaded': 'لم يكتمل الرفع. حاول مرة أخرى.',
    'setting.not-configured': 'لم يتم إعداد هذا بعد. يرجى التواصل مع المسؤول.',
  },
};
