import type { TextShape } from '../text-shape';
import type { electionsText as english } from '../en/elections';

export const electionsText: TextShape<typeof english> = {
  noElections: 'لم تُسجَّل انتخابات بعد.',
  recordHeading: 'تسجيل انتخابات',
  electionDate: 'تاريخ الانتخابات',
  corrects: 'تصحيح لـ',
  notACorrection: 'ليست تصحيحًا',
  record: 'تسجيل الانتخابات',
  correction: 'تصحيح لانتخابات سابقة معتمدة',
  statuses: { Draft: 'مسودة', Confirmed: 'معتمدة' },
  electionOf: 'انتخابات {date}',
  termsStarted: 'بدأت فترات العضوية الجديدة في {date}',
  locked: 'هذه الانتخابات معتمدة ومقفلة. يُسجَّل التصحيح انتخاباتٍ جديدة.',
  positions: 'المناصب الانتخابية',
  noPositions: 'لا توجد مناصب انتخابية بعد.',
  seats: 'المقاعد',
  seatCount: '{seats} مقعد',
  addPosition: 'إضافة منصب انتخابي',
  removePosition: 'إزالة منصب {role}',
  candidate: 'المرشح',
  chooseCandidate: 'اختر مرشحًا',
  someoneNew: 'شخص جديد',
  addCandidate: 'إضافة مرشح',
  removeCandidate: 'إزالة {name}',
  votes: '{votes} صوتًا',
  votesFor: 'أصوات {name}',
  elected: 'فائز',
  results: 'النتائج',
  saveResults: 'حفظ النتائج',
  confirmExplanation:
    'يؤدي الاعتماد إلى إنهاء فترات العضوية المنتهية وبدء فترات الفائزين في التاريخ أدناه. ولا يمكن التراجع عنه.',
  confirmChecked: 'راجعتُ النتائج.',
  termsStartDate: 'تبدأ فترات العضوية الجديدة في',
  confirm: 'اعتماد النتائج',
  refusals: {
    'elections.confirmed-is-locked': 'هذه الانتخابات معتمدة ومقفلة.',
    'elections.corrects-must-be-confirmed-of-unit':
      'يجب أن يشير التصحيح إلى انتخابات معتمدة لهذه الوحدة.',
    'elections.start-before-election': 'لا يمكن أن تبدأ فترات العضوية الجديدة قبل الانتخابات.',
    'elections.no-positions': 'أضف منصبًا انتخابيًا واحدًا على الأقل أولًا.',
    'elections.results-incomplete': 'سجّل أصوات كل المرشحين أولًا.',
    'elections.seats-not-filled': 'يجب أن يكون عدد الفائزين في كل منصب مساويًا تمامًا لعدد مقاعده.',
    'elections.already-a-candidate': 'هذا الشخص مرشح لهذا المنصب بالفعل.',
    'elections.position-not-found': 'لم يعد هذا المنصب الانتخابي موجودًا.',
    'elections.candidate-not-found': 'لم يعد هذا المرشح موجودًا.',
    'elections.not-found': 'لم تعد هذه الانتخابات موجودة.',
    'roles.not-found': 'لا يمكن استخدام هذا الدور في هذه الوحدة.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا سجله للقراءة فقط.',
    'setting.not-configured':
      'ينتظر هذا مسؤول البيانات: لم تُضبط اللغة التي يبدأ بها أعضاء اللجان الجدد.',
    'request.invalid': 'تحقّق من الحقول وحاول مرة أخرى.',
  },
};
