import type { TextShape } from '../text-shape';
import type { equipmentText as english } from '../en/equipment';

export const equipmentText: TextShape<typeof english> = {
  heading: 'المعدات',
  none: 'لا توجد معدات بعد.',
  add: 'إضافة معدات',
  item: 'الصنف',
  quantity: 'الكمية',
  location: 'مكان الحفظ',
  condition: 'الحالة',
  noConditions: 'قائمة حالات المعدات فارغة، فلا يمكن اختيار حالة بعد. يرجى التواصل مع المسؤول.',
  optional: '{label} (اختياري)',
  quantityIs: 'الكمية: {quantity}',
  keptAt: 'مكان الحفظ: {location}',
  conditionIs: 'الحالة: {condition}',
  outOnLoan: '{count} معارة',
  save: 'حفظ',
  cancel: 'إلغاء',
  edit: 'تعديل التفاصيل',
  retire: 'إيقاف',
  restore: 'إعادة',
  national: 'المجلس العام',
  retired: 'موقوف',
  onLoanNow: 'المعار حاليًا',
  nothingOut: 'لا شيء معار حاليًا.',
  loans: 'الإعارات',
  lend: 'إعارة',
  borrower: 'المستعير',
  borrowedOn: 'تاريخ الإعارة',
  dueBack: 'موعد الإرجاع',
  returnedOn: 'تاريخ الإرجاع الفعلي',
  loanSummary: '{quantity} × {item} إلى {borrower}، من {borrowed}، موعد الإرجاع {due}',
  loanReturned: 'أُرجعت في {date}',
  correct: 'تصحيح',
  recordReturn: 'تسجيل الإرجاع',
  history: 'السجل',
  changes: { lent: 'أُعيرت', corrected: 'صُحّحت', returned: 'أُرجعت' },
  historyEntry:
    '{change} بواسطة {name} في {date}: {quantity} إلى {borrower}، من {borrowed} إلى {due}',
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'resources-library.stale': 'عدّل شخص آخر هذا. أعد تحميل الصفحة لترى تعديله.',
    'resources-library.equipment-not-found': 'هذا الصنف لم يعد موجودًا.',
    'resources-library.loan-not-found': 'هذه الإعارة لم تعد موجودة.',
    'resources-library.already-retired': 'هذا الصنف موقوف بالفعل.',
    'resources-library.not-retired': 'هذا الصنف غير موقوف.',
    'resources-library.condition-not-offered': 'اختر حالة من القائمة.',
    'resources-library.equipment-retired': 'هذا الصنف موقوف، فلا يمكن إعارته.',
    'resources-library.over-lent':
      'المتبقي للإعارة {left} فقط: المملوك {quantity} والمعار حاليًا {out}. طلبت {requested}.',
    'resources-library.below-loans': 'لا يمكن أن تكون الكمية {quantity}: المعار حاليًا {out}.',
    'resources-library.loan-returned': 'أُرجعت هذه الإعارة، فلم يعد بالإمكان تغييرها.',
    'resources-library.returned-before-borrowed': 'لا يمكن أن يُرجع قبل يوم إعارته.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فمكتبته للاطلاع فقط.',
    'request.invalid': 'راجع التفاصيل: موعد الإرجاع في يوم الإعارة أو بعده.',
  },
};
