import type { TextShape } from '../text-shape';
import type { eventOrganiserText as english } from '../en/event-organiser';

export const eventOrganiserText: TextShape<typeof english> = {
  name: 'منظّم الفعاليات',
  capabilities: {
    'event-organiser.events.read': 'الاطلاع على الفعاليات',
    'event-organiser.events.create': 'إنشاء الفعاليات',
    'event-organiser.events.approve': 'اعتماد الفعاليات',
    'event-organiser.events.manage': 'إدارة الفعاليات',
    'event-organiser.events.close': 'إغلاق الفعاليات',
    'event-organiser.templates.manage': 'إدارة قوالب الفعاليات',
  },
  settings: {
    'event-organiser.status_may_move_backwards': 'السماح بإرجاع حالة الفعالية إلى الوراء',
    'event-organiser.cancelled_tasks_count_in_progress': 'احتساب المهام الملغاة في نسبة الإنجاز',
  },
  sections: { label: 'أقسام منظّم الفعاليات', events: 'الفعاليات', templates: 'القوالب' },
  list: { heading: 'الفعاليات', none: 'لا توجد فعاليات بعد.', add: 'فعالية جديدة' },
  form: {
    name: 'الاسم',
    type: 'النوع',
    lead: 'المسؤول عن الفعالية',
    firstDay: 'التاريخ (اليوم الأول)',
    startTime: 'وقت البدء (اختياري)',
    lastDay: 'اليوم الأخير (اختياري، لفعالية تمتد عدة أيام)',
    template: 'البدء من قالب (اختياري)',
    noTemplate: 'بدون قالب',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  details: { when: 'الموعد', cancelled: 'أُلغيت: {reason}', edit: 'تعديل التفاصيل' },
  status: {
    heading: 'الحالة',
    approve: 'تسجيل اعتماد اللجنة',
    moveTo: 'النقل إلى {status}',
    moveBackTo: 'الإرجاع إلى {status}',
    cancel: 'إلغاء الفعالية',
    cancelWarning:
      'لا يمكن التراجع عن الإلغاء. تُغلق الفعالية بعد ذلك بالطريقة المعتادة على أنها ملغاة.',
    reason: 'سبب الإلغاء',
    confirmCancel: 'إلغاء الفعالية',
  },
  publish: {
    heading: 'النشر',
    targets: { calendar: 'التقويم', noticeboard: 'لوحة الإعلانات' },
    published: 'نُشرت في {target} بتاريخ {date}.',
    notYet: 'لم تُنشر في {target} بعد.',
    switchedOff: 'لم تُنشر في {target}: الخدمة متوقفة. يمكن نشرها عند إعادة تشغيلها.',
    publishTo: 'النشر في {target}',
    publishAll: 'النشر في كليهما',
    cancellationPosted: 'نُشر الإلغاء على لوحة الإعلانات.',
    cancellationWaiting: 'لم يُنشر الإلغاء على لوحة الإعلانات بعد.',
    cancellationSkipped: 'تعذّر نشر الإلغاء: لوحة الإعلانات متوقفة. يمكن نشره عند إعادة تشغيلها.',
    postCancellation: 'نشر الإلغاء',
  },
  tasks: {
    heading: 'المهام',
    progress: 'أُنجزت {done} من {total} مهام',
    overdue: '{count} متأخرة',
    add: 'إضافة مهمة',
    remove: 'إزالة',
  },
  account: {
    heading: 'حساب الفعالية',
    income: 'الإيرادات',
    spending: 'المصروفات',
    balance: 'الرصيد',
    receipts: 'الإيصالات',
    awaiting: '{count} بانتظار الاعتماد في الخزينة.',
    budgetLines: 'بنود الميزانية',
    change: 'تعديل',
    remove: 'إزالة',
    addLine: 'إضافة بند ميزانية',
    lineName: 'بند الميزانية',
    lineAmount: 'المبلغ (£)',
    openInTreasury: 'فتح الحساب في الخزينة',
  },
  files: {
    heading: 'ملفات الفعالية',
    sections: { Documents: 'المستندات', Media: 'الوسائط' },
    section: 'القسم',
    file: 'الملف',
    add: 'إضافة الملف',
    remove: 'إزالة',
  },
  volunteers: { heading: 'المتطوعون', comingSoon: 'قريبًا' },
  close: {
    heading: 'إغلاق الفعالية',
    overspent:
      'تجاوزت هذه الفعالية ميزانيتها بمبلغ {amount}. يؤخذ عند الإغلاق مبلغ {amount} من حساب الفرع المختار لتصفيرها.',
    returned: 'يعيد الإغلاق الرصيد البالغ {amount} إلى حساب الفرع المختار.',
    explain: 'يُحفظ تقرير ما بعد الفعالية وكل ملفات الفعالية في الأرشيف، وتُقفل الفعالية ومهامها.',
    account: 'حساب الفرع',
    confirm: 'إغلاق الفعالية',
  },
  templates: {
    heading: 'قوالب الفعاليات',
    none: 'لا توجد قوالب بعد.',
    add: 'قالب جديد',
    name: 'اسم القالب',
    tasks: 'المهام الافتراضية',
    taskTitle: 'المهمة',
    taskDescription: 'الوصف (اختياري)',
    daysBefore: 'عدد الأيام قبل اليوم الأول',
    removeRow: 'إزالة',
    addTask: 'إضافة مهمة',
    budgetLines: 'بنود الميزانية الافتراضية',
    lineName: 'بند الميزانية',
    lineAmount: 'المبلغ (£)',
    addLine: 'إضافة بند ميزانية',
    retired: 'موقوف',
    summary: '{tasks} مهام، {lines} بنود ميزانية',
    change: 'تعديل',
    retire: 'إيقاف',
    restore: 'إعادة',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فعالياته للقراءة فقط.',
    'setting.not-configured': 'لم يُضبط هذا بعد. يُرجى مراجعة المسؤول.',
    'request.invalid': 'تحقّق من التفاصيل وحاول مرة أخرى.',
    'pdf.not-available': 'ملفات PDF غير متاحة هنا. تعمل على موقع المعاينة.',
    'files.type-not-allowed': 'نوع هذا الملف غير مسموح به هنا.',
    'files.too-large': 'هذا الملف أكبر من الحد المسموح.',
    'files.storage-not-configured': 'لم يُضبط تخزين الملفات بعد.',
    'files.upload-failed': 'لم يكتمل الرفع. حاول مرة أخرى.',
    'files.not-uploaded': 'لم يكتمل الرفع. حاول مرة أخرى.',
    'files.photo-not-readable': 'تعذّرت قراءة هذه الصورة.',
    'task-tracker.owner-not-an-officer': 'اختر أحد مسؤولي الوحدة الحاليين مسؤولًا عن المهمة.',
    'task-tracker.task-not-found': 'هذه المهمة غير موجودة.',
    'treasury.not-an-open-branch-account': 'اختر أحد حسابات الفرع المفتوحة.',
    'treasury.account-closed': 'حساب الفعالية مغلق بالفعل.',
    'event-organiser.stale': 'غيّر شخص آخر هذه الفعالية. أعد تحميل الصفحة لرؤية التغيير.',
    'event-organiser.locked': 'هذه الفعالية مغلقة ومقفلة.',
    'event-organiser.event-not-found': 'هذه الفعالية غير موجودة.',
    'event-organiser.template-not-found': 'هذا القالب غير موجود.',
    'event-organiser.type-not-in-list': 'اختر نوعًا من القائمة.',
    'event-organiser.lead-not-an-officer': 'اختر أحد مسؤولي الوحدة الحاليين مسؤولًا عن الفعالية.',
    'event-organiser.own-event': 'أنت من أنشأ هذه الفعالية، لذا يجب أن يعتمدها مسؤول آخر.',
    'event-organiser.not-a-draft': 'لا تُعتمد إلا الفعالية في حالة المسودة.',
    'event-organiser.status-move-not-allowed': 'هذا الانتقال في الحالة غير مسموح.',
    'event-organiser.not-cancellable': 'لم يعد بالإمكان إلغاء هذه الفعالية.',
    'event-organiser.not-cancelled': 'هذه الفعالية ليست ملغاة.',
    'event-organiser.nothing-to-post': 'لا يوجد إلغاء لنشره.',
    'event-organiser.not-publishable': 'لا يمكن نشر هذه الفعالية الآن.',
    'event-organiser.budget-fixed': 'تُثبّت الميزانية بعد اعتماد الفعالية.',
    'event-organiser.budget-line-not-found': 'بند الميزانية هذا غير موجود.',
    'event-organiser.budget-line-tagged': 'سُجّلت مبالغ على بند الميزانية هذا، لذا لا يمكن إزالته.',
    'event-organiser.use-not-in-section': 'هذا النوع من الملفات لا يوضع في ذلك القسم.',
    'event-organiser.file-not-found': 'هذا الملف غير موجود.',
    'event-organiser.report-not-ready': 'يتاح تقرير ما بعد الفعالية بعد اكتمالها.',
    'event-organiser.not-closable': 'لا تُغلق إلا الفعالية المكتملة أو الملغاة.',
    'event-organiser.amount-invalid':
      'اكتب كل مبلغ بالجنيه، مثل 150 أو 150.50، وكل عدد أيام رقمًا صحيحًا.',
  },
  statuses: {
    Draft: 'مسودة',
    Approved: 'معتمدة',
    'In preparation': 'قيد التحضير',
    Ready: 'جاهزة',
    Completed: 'مكتملة',
    Cancelled: 'ملغاة',
    Closed: 'مغلقة',
  },
  reportPdf: {
    title: 'تقرير ما بعد الفعالية: {name}',
    titleCancelled: 'تقرير ما بعد الفعالية: {name} (ملغاة)',
    dates: 'التاريخ: {dates}',
    type: 'النوع: {type}',
    lead: 'المسؤول عن الفعالية: {name}',
    cancelReason: 'أُلغيت: {reason}',
    tasksHeading: 'المهام',
    tasksSummary: 'أُنجزت {done} من {total} مهام',
    taskHeadings: { task: 'المهمة', status: 'الحالة' },
    budgetHeading: 'الميزانية مقابل الفعلي',
    budgetHeadings: {
      line: 'بند الميزانية',
      budget: 'الميزانية',
      income: 'الإيرادات',
      spending: 'المصروفات',
    },
    unallocated: 'غير مخصص',
    totals: 'الإجمالي',
    balance: 'الرصيد النهائي',
  },
};
