import type { TextShape } from '../text-shape';
import type { meetingRecorderText as english } from '../en/meeting-recorder';

export const meetingRecorderText: TextShape<typeof english> = {
  name: 'سجلّ الاجتماعات',
  capabilities: {
    'meeting-recorder.meetings.read': 'الاطلاع على الاجتماعات',
    'meeting-recorder.meetings.manage': 'إدارة الاجتماعات',
  },
  settings: {
    'meeting-recorder.minutes_autosave_seconds': 'فترة الحفظ التلقائي للمحضر (بالثواني)',
  },
  list: { heading: 'الاجتماعات', none: 'لا توجد اجتماعات بعد.', add: 'اجتماع جديد' },
  form: {
    type: 'النوع',
    date: 'التاريخ',
    startTime: 'وقت البدء',
    place: 'المكان (أو أدخل رابطًا إلكترونيًا)',
    onlineLink: 'الرابط الإلكتروني (أو أدخل مكانًا)',
    chair: 'الرئيس',
    secretary: 'أمين السر',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  details: { when: 'الموعد', cancelled: 'أُلغي: {reason}', edit: 'تعديل التفاصيل' },
  status: {
    hold: 'بدأ الاجتماع: تسجيله منعقدًا',
    log: 'تسجيل التقرير',
    download: 'تنزيل التقرير',
    cancel: 'إلغاء الاجتماع',
    cancelWarning: 'يُزال الاجتماع الملغى من التقويم ولا يمكن إعادته.',
    reason: 'سبب الإلغاء',
    confirmCancel: 'إلغاء الاجتماع',
  },
  attendees: {
    heading: 'الحضور',
    mark: 'حضور',
    notMarked: 'لم يُحدَّد',
    remove: 'إزالة',
    add: 'إضافة حضور',
    addChosen: 'إضافة المسؤولين المختارين',
  },
  agenda: {
    heading: 'جدول الأعمال',
    up: 'تحريك لأعلى',
    down: 'تحريك لأسفل',
    change: 'تعديل',
    remove: 'إزالة',
    add: 'إضافة بند',
    addRaised: 'إضافة نقطة طُرحت في الاجتماع',
    title: 'البند',
    note: 'ملاحظة (اختياري)',
  },
  minutes: {
    heading: 'المحضر',
    theirs: 'حفظ شخص آخر هذا التعليق هكذا:',
    saved: 'حُفظ',
    save: 'حفظ',
  },
  outcome: {
    kind: 'انتهى بـ',
    decision: 'قرار',
    vote: 'تصويت',
    for: 'مع',
    against: 'ضد',
    abstain: 'ممتنع',
    result: 'النتيجة',
    decisionText: 'القرار',
    save: 'حفظ النتيجة',
  },
  targets: {
    notSent: {
      calendar: 'لم يُضَف إلى التقويم بعد.',
      'meeting-scheduled': 'لم يُنشر إعلان «تحديد موعد الاجتماع» بعد.',
      'meeting-held': 'لم يُنشر إعلان «انعقاد الاجتماع» بعد.',
    },
    skipped: {
      calendar: 'لم يُضَف إلى التقويم: كان متوقفًا. يمكن إضافته عند إعادة تشغيله.',
      'meeting-scheduled':
        'لم يُنشر إعلان «تحديد موعد الاجتماع»: كانت لوحة الإعلانات متوقفة. يمكن نشره عند إعادة تشغيلها.',
      'meeting-held':
        'لم يُنشر إعلان «انعقاد الاجتماع»: كانت لوحة الإعلانات متوقفة. يمكن نشره عند إعادة تشغيلها.',
    },
    send: {
      calendar: 'إضافة إلى التقويم',
      'meeting-scheduled': 'نشر «تحديد موعد الاجتماع»',
      'meeting-held': 'نشر «انعقاد الاجتماع»',
    },
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا اجتماعاته للقراءة فقط.',
    'setting.not-configured': 'لم يُضبط هذا بعد. يُرجى مراجعة المسؤول.',
    'request.invalid': 'تحقّق من التفاصيل وحاول مرة أخرى.',
    'pdf.not-available': 'ملفات PDF غير متاحة هنا. تعمل على موقع المعاينة.',
    'meeting-recorder.stale': 'غيّر شخص آخر هذا. أعد تحميل الصفحة لرؤية التغيير.',
    'meeting-recorder.locked': 'هذا الاجتماع مقفل.',
    'meeting-recorder.meeting-not-found': 'هذا الاجتماع غير موجود.',
    'meeting-recorder.type-not-in-list': 'اختر نوعًا من القائمة.',
    'meeting-recorder.not-an-officer': 'اختر من مسؤولي الوحدة الحاليين.',
    'meeting-recorder.wrong-status': 'لا يمكن القيام بهذا في هذه المرحلة من الاجتماع.',
    'meeting-recorder.not-yet': 'يمكن تسجيل انعقاد الاجتماع ابتداءً من تاريخه.',
    'meeting-recorder.chair-or-secretary': 'يحضر الرئيس وأمين السر دائمًا.',
    'meeting-recorder.has-comments': 'لهذا المسؤول تعليقات في المحضر، لذا يبقى حاضرًا.',
    'meeting-recorder.attendee-not-found': 'هذا المسؤول ليس من الحضور.',
    'meeting-recorder.item-not-found': 'هذا البند غير موجود.',
    'meeting-recorder.original-agenda-fixed': 'يُثبَّت جدول الأعمال الأصلي بعد انعقاد الاجتماع.',
    'meeting-recorder.agenda-changed': 'تغيّر جدول الأعمال. أعد تحميل الصفحة وحاول مرة أخرى.',
    'meeting-recorder.not-present': 'تُسجَّل التعليقات للمسؤولين الحاضرين.',
    'meeting-recorder.too-many-votes': 'مجموع الأصوات أكبر من عدد الحاضرين.',
    'meeting-recorder.count-invalid': 'اكتب كل عدد أصوات رقمًا صحيحًا.',
    'meeting-recorder.attendance-unmarked': 'حدّد حضور كل المدعوين قبل تسجيل التقرير.',
    'meeting-recorder.item-without-outcome': 'أعطِ كل بند تصويتًا أو قرارًا قبل تسجيل التقرير.',
    'meeting-recorder.nothing-to-send': 'لا يوجد ما يُرسل.',
    'meeting-recorder.service-off': 'هذه الخدمة متوقفة.',
    'meeting-recorder.report-not-logged': 'لم يُسجَّل التقرير بعد.',
  },
  statuses: {
    Scheduled: 'مجدول',
    Held: 'منعقد',
    'Report logged': 'سُجّل التقرير',
    Cancelled: 'ملغى',
  },
  attendance: {
    Present: 'حاضر',
    Apologies: 'معتذر',
    'Did not attend': 'لم يحضر',
  },
  reportPdf: {
    title: 'تقرير الاجتماع: {type}',
    when: 'التاريخ: {date}، {time}',
    place: 'المكان: {place}',
    link: 'عبر الإنترنت: {link}',
    chair: 'الرئيس: {name}',
    secretary: 'أمين السر: {name}',
    attendance: 'الحضور',
    notMarked: 'لم يُحدَّد',
    originalAgenda: 'جدول الأعمال',
    updatedAgenda: 'جدول الأعمال كما حُدّث في الاجتماع',
    raised: '{title} (طُرح في الاجتماع)',
    recordedFor: 'سجّله {recorder} نيابةً عن {officer}',
    minutes: 'المحضر',
    vote: 'التصويت: {for} مع، {against} ضد، {abstain} ممتنع. النتيجة: {result}',
    decision: 'القرار: {decision}',
  },
};
