import type { TextShape } from '../text-shape';
import type { taskTrackerText as english } from '../en/task-tracker';

export const taskTrackerText: TextShape<typeof english> = {
  name: 'متابعة المهام',
  capabilities: {
    'task-tracker.tasks.read': 'الاطلاع على قائمة المهام',
    'task-tracker.tasks.manage': 'إدارة المهام',
  },
  settings: {
    'task-tracker.due_soon_window_days': 'مدة "قريبة الاستحقاق" (أيام)',
    'task-tracker.reminder_days_before': 'التذكير (أيام قبل موعد الاستحقاق)',
  },
  sections: { label: 'أقسام متابعة المهام', mine: 'مهامي', actionList: 'قائمة المهام' },
  statuses: { 'To do': 'للتنفيذ', 'In progress': 'قيد التنفيذ', Done: 'منجزة', Cancelled: 'ملغاة' },
  mine: { heading: 'مهامي', none: 'لا توجد لديك مهام.' },
  actionList: {
    heading: 'قائمة المهام',
    none: 'لا توجد مهام مطابقة.',
    filters: 'التصفية',
    owner: 'المسؤول',
    status: 'الحالة',
    any: 'الكل',
    apply: 'عرض',
  },
  flags: { dueSoon: 'قريبة الاستحقاق', overdue: 'متأخرة' },
  due: 'تستحق في {date}',
  ownedBy: 'المسؤول: {name}',
  eventTask: 'مهمة فعالية',
  add: 'إضافة مهمة',
  edit: 'تعديل',
  form: {
    title: 'العنوان',
    description: 'الوصف (اختياري)',
    owner: 'المسؤول',
    dueDate: 'موعد الاستحقاق',
    status: 'الحالة',
    save: 'حفظ',
    cancel: 'إلغاء',
  },
  statusLabel: 'حالة {title}',
  history: {
    show: 'السجل',
    created: 'أنشأها {name} في {date}',
    changed: 'عدّلها {name} في {date}',
    change: '{field}: {before} ← {after}',
    fields: {
      title: 'العنوان',
      description: 'الوصف',
      ownerPersonId: 'المسؤول',
      dueDate: 'موعد الاستحقاق',
      status: 'الحالة',
    },
    empty: '(لا شيء)',
  },
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فمهامه للاطلاع فقط.',
    'setting.not-configured': 'لم يتم إعداد هذا بعد. يرجى التواصل مع المسؤول.',
    'request.invalid': 'راجع التفاصيل وحاول مرة أخرى.',
    'task-tracker.task-not-found': 'هذه المهمة غير موجودة.',
    'task-tracker.owner-not-an-officer': 'اختر أحد المسؤولين الحاليين في الوحدة.',
    'task-tracker.stale': 'عدّل شخص آخر هذه المهمة. أعد تحميل الصفحة لترى تعديله.',
  },
};
