import type { TextShape } from '../text-shape';
import type { treasuryEntriesText as english } from '../en/treasury-entries';

export const treasuryEntriesText: TextShape<typeof english> = {
  heading: 'القيود',
  none: 'لا توجد قيود في هذه الفترة.',
  record: { credit: 'تسجيل إيراد', debit: 'تسجيل مصروف', transfer: 'تسجيل تحويل' },
  types: { 'opening-balance': 'رصيد افتتاحي', credit: 'إيراد', debit: 'مصروف', transfer: 'تحويل' },
  transferTo: 'تحويل إلى {account}',
  transferFrom: 'تحويل من {account}',
  approvalStatuses: {
    'Awaiting approval': 'بانتظار الاعتماد',
    Approved: 'معتمد',
    Declined: 'مرفوض',
  },
  account: 'الحساب',
  toAccount: 'إلى الحساب',
  amount: 'المبلغ (£)',
  date: 'التاريخ',
  source: 'المصدر',
  paidTo: 'المدفوع له',
  description: 'الوصف',
  budgetLine: 'بند الميزانية (اختياري)',
  receipts: 'صور الإيصالات',
  receiptsHint: 'التقط صورة بالكاميرا، أو اختر صورة.',
  takePhoto: 'التقاط صورة',
  choosePhoto: 'اختيار صورة',
  photosChosen: '{count} صورة جاهزة',
  save: 'حفظ',
  done: 'تم',
  cancel: 'إلغاء',
  amountInvalid: 'اكتب المبلغ بالجنيه، مثل 150 أو 20.50.',
  willGoBelowZero: 'هذا ينزل برصيد {account} دون الصفر. سيُحفظ مع تنبيه.',
  enteredBy: 'سجّله {name} في {date}',
  decidedBy: '{status} بواسطة {name} في {date}',
  declineReason: 'السبب: {reason}',
  reversalOf: 'يعكس قيدًا سابقًا',
  reversedBy: 'عُكس بقيد لاحق',
  noReceipt: 'لا إيصال',
  addReceipt: 'إضافة إيصال',
  download: 'الإيصال {number}',
  correct: 'تصحيح',
  correctExplanation:
    'يسجّل هذا قيدًا عكسيًا بتاريخ اليوم يلغي هذا القيد. ثم سجّل القيد الصحيح قيدًا جديدًا.',
  correctNote: 'السبب (اختياري)',
  confirmCorrect: 'تسجيل القيد العكسي',
  period: { from: 'من', to: 'إلى', show: 'عرض' },
  warnings: {
    'below-zero': 'رصيد {account} الآن دون الصفر: {balance}.',
    'no-receipt': 'حُفظ دون إيصال. يمكنك إضافته لاحقًا.',
  },
  saved: {
    'Not needed': 'تم الحفظ.',
    'Awaiting approval': 'تم الحفظ. هو فوق حد الاعتماد، لذا ينتظر اعتماد مسؤول آخر.',
  },
};
