import type { TextShape } from '../text-shape';
import type { treasuryRefusalsText as english } from '../en/treasury-refusals';

export const treasuryRefusalsText: TextShape<typeof english> = {
  'permission.denied': 'لا يحق لك القيام بذلك.',
  'branches.inactive': 'هذا الفرع غير نشط، لذا فخزينته للاطلاع فقط.',
  'setting.not-configured': 'لم يتم إعداد هذا بعد. يرجى التواصل مع المسؤول.',
  'pdf.not-available': 'ملفات PDF غير متاحة هنا. تعمل في موقع المعاينة.',
  'request.invalid': 'راجع التفاصيل وحاول مرة أخرى.',
  'treasury.account-not-found': 'هذا الحساب غير موجود.',
  'treasury.account-closed': 'هذا الحساب مغلق، فلا يقبل قيودًا جديدة.',
  'treasury.not-zero': 'لا يُغلق هذا الحساب إلا عند رصيد صفر ولا شيء بانتظار الاعتماد.',
  'treasury.event-account-by-event-organiser': 'حسابات الفعاليات يغلقها منظم الفعاليات.',
  'treasury.future-date': 'لا يمكن تأريخ قيد في المستقبل.',
  'treasury.closed-year': 'هذا التاريخ في سنة مالية مُقفلة، قيودها مقفلة.',
  'treasury.receipt-required': 'صورة الإيصال مطلوبة لهذا.',
  'treasury.budget-line-not-of-account': 'اختر بند ميزانية من هذا الحساب.',
  'treasury.entry-exists': 'حُفظ هذا القيد من قبل.',
  'treasury.entry-not-found': 'هذا القيد غير موجود.',
  'treasury.receipt-not-found': 'هذا الإيصال غير موجود.',
  'treasury.not-awaiting': 'لم يعد هذا بانتظار الاعتماد.',
  'treasury.self-approval': 'أنت سجّلت هذا، فيجب أن يقرره مسؤول آخر.',
  'treasury.reason-required': 'اذكر سبب الرفض.',
  'treasury.already-reversed': 'عُكس هذا القيد من قبل.',
  'treasury.reversal-not-reversed': 'لا يمكن عكس قيد عكسي.',
  'treasury.not-counted': 'لا يُعكس إلا قيد محتسب.',
  'treasury.statement-already-filed': 'حُفظ هذا الكشف من قبل.',
  'treasury.not-a-year-start': 'هذا ليس بداية سنة مالية.',
  'treasury.year-closed': 'هذه السنة مُقفلة بالفعل.',
  'treasury.year-not-ended': 'لم تنتهِ هذه السنة بعد.',
  'treasury.earlier-year-open': 'أقفل السنة المالية السابقة أولًا.',
  'treasury.awaiting-in-year': '{awaiting} مؤرخة في هذه السنة بانتظار الاعتماد. قرّرها أولًا.',
  'files.type-not-allowed': 'نوع هذا الملف غير مسموح به لصور الإيصالات.',
  'files.too-large': 'حجم هذه الصورة أكبر من الحد المسموح به لصور الإيصالات.',
  'files.storage-not-configured': 'لم يُجهَّز تخزين الملفات بعد.',
  'files.upload-failed': 'لم يكتمل الرفع. حاول مرة أخرى.',
  'files.not-uploaded': 'لم يكتمل الرفع. حاول مرة أخرى.',
};
