import type { TextShape } from '../text-shape';
import type { venuesText as english } from '../en/venues';

export const venuesText: TextShape<typeof english> = {
  heading: 'القاعات',
  none: 'لا توجد قاعات بعد.',
  add: 'إضافة قاعة',
  name: 'الاسم',
  address: 'العنوان',
  capacity: 'السعة',
  facilities: 'المرافق',
  contactName: 'الشخص المسؤول',
  contactPhone: 'هاتف المسؤول',
  contactEmail: 'بريد المسؤول الإلكتروني',
  typicalCost: 'التكلفة المعتادة (£)',
  typicalCostNote: 'ما تشمله التكلفة',
  optional: '{label} (اختياري)',
  costInvalid: 'اكتب التكلفة بالجنيه، مثل 150 أو 150.50.',
  people: '{count} شخصًا',
  save: 'حفظ',
  cancel: 'إلغاء',
  edit: 'تعديل التفاصيل',
  retire: 'إيقاف',
  restore: 'إعادة',
  national: 'المجلس العام',
  retired: 'موقوفة',
  notes: 'ملاحظات من الاستخدام السابق',
  noNotes: 'لا توجد ملاحظات بعد.',
  noteBy: '{name}، {date}',
  noteOn: '{date}',
  newNote: 'إضافة ملاحظة',
  addNote: 'إضافة الملاحظة',
  retireNote: 'إيقاف الملاحظة',
  refusals: {
    'permission.denied': 'لا يحق لك القيام بذلك.',
    'resources-library.stale': 'عدّل شخص آخر هذه القاعة. أعد تحميل الصفحة لترى تعديله.',
    'resources-library.venue-not-found': 'هذه القاعة لم تعد موجودة.',
    'resources-library.venue-note-not-found': 'هذه الملاحظة لم تعد ظاهرة.',
    'resources-library.already-retired': 'هذه القاعة موقوفة بالفعل.',
    'resources-library.not-retired': 'هذه القاعة غير موقوفة.',
    'branches.inactive': 'هذا الفرع غير نشط، لذا فمكتبته للاطلاع فقط.',
  },
};
